const overdoseData = [
  {
    YEAR: 2022,
    STATE: 'AL',
    RATE: 31.5,
    DEATHS: 1492,
    URL: '/nchs/pressroom/states/alabama/al.htm',
  },
  {
    YEAR: 2022,
    STATE: 'AK',
    RATE: 34.3,
    DEATHS: 254,
    URL: '/nchs/pressroom/states/alaska/ak.htm',
  },
  {
    YEAR: 2022,
    STATE: 'AZ',
    RATE: 37.2,
    DEATHS: 2664,
    URL: '/nchs/pressroom/states/arizona/az.htm',
  },
  {
    YEAR: 2022,
    STATE: 'AR',
    RATE: 21.7,
    DEATHS: 617,
    URL: '/nchs/pressroom/states/arkansas/ar.htm',
  },
  {
    YEAR: 2022,
    STATE: 'CA',
    RATE: 26.9,
    DEATHS: 10952,
    URL: '/nchs/pressroom/states/california/ca.htm',
  },
  {
    YEAR: 2022,
    STATE: 'CO',
    RATE: 29.8,
    DEATHS: 1811,
    URL: '/nchs/pressroom/states/colorado/co.htm',
  },
  {
    YEAR: 2022,
    STATE: 'CT',
    RATE: 40.3,
    DEATHS: 1482,
    URL: '/nchs/pressroom/states/connecticut/ct.htm',
  },
  {
    YEAR: 2022,
    STATE: 'DE',
    RATE: 55.3,
    DEATHS: 549,
    URL: '/nchs/pressroom/states/delaware/de.htm',
  },
  {
    YEAR: 2022,
    STATE: 'District of Columbia',
    RATE: 64.3,
    DEATHS: 451,
    URL: '/nchs/pressroom/states/DC/DC1.htm',
  },
  {
    YEAR: 2022,
    STATE: 'FL',
    RATE: 35.2,
    DEATHS: 7551,
    URL: '/nchs/pressroom/states/florida/fl.htm',
  },
  {
    YEAR: 2022,
    STATE: 'GA',
    RATE: 24.9,
    DEATHS: 2687,
    URL: '/nchs/pressroom/states/georgia/ga.htm',
  },
  {
    YEAR: 2022,
    STATE: 'HI',
    RATE: 18.6,
    DEATHS: 284,
    URL: '/nchs/pressroom/states/hawaii/hi.htm',
  },
  {
    YEAR: 2022,
    STATE: 'ID',
    RATE: 20.7,
    DEATHS: 385,
    URL: '/nchs/pressroom/states/idaho/id.htm',
  },
  {
    YEAR: 2022,
    STATE: 'IL',
    RATE: 30.0,
    DEATHS: 3849,
    URL: '/nchs/pressroom/states/illinois/il.htm',
  },
  {
    YEAR: 2022,
    STATE: 'IN',
    RATE: 41.0,
    DEATHS: 2682,
    URL: '/nchs/pressroom/states/indiana/in.htm',
  },
  {
    YEAR: 2022,
    STATE: 'IA',
    RATE: 15.3,
    DEATHS: 469,
    URL: '/nchs/pressroom/states/iowa/ia.htm',
  },
  {
    YEAR: 2022,
    STATE: 'KS',
    RATE: 26.5,
    DEATHS: 754,
    URL: '/nchs/pressroom/states/kansas/ks.htm',
  },
  {
    YEAR: 2022,
    STATE: 'KY',
    RATE: 53.2,
    DEATHS: 2271,
    URL: '/nchs/pressroom/states/kentucky/ky.htm',
  },
  {
    YEAR: 2022,
    STATE: 'LA',
    RATE: 54.5,
    DEATHS: 2376,
    URL: '/nchs/pressroom/states/louisiana/la.htm',
  },
  {
    YEAR: 2022,
    STATE: 'ME',
    RATE: 54.3,
    DEATHS: 707,
    URL: '/nchs/pressroom/states/maine/me.htm',
  },
  {
    YEAR: 2022,
    STATE: 'MD',
    RATE: 40.3,
    DEATHS: 2573,
    URL: '/nchs/pressroom/states/maryland/md.htm',
  },
  {
    YEAR: 2022,
    STATE: 'MA',
    RATE: 37.4,
    DEATHS: 2642,
    URL: '/nchs/pressroom/states/massachusetts/ma.htm',
  },
  {
    YEAR: 2022,
    STATE: 'MI',
    RATE: 30.7,
    DEATHS: 2997,
    URL: '/nchs/pressroom/states/michigan/mi.htm',
  },
  {
    YEAR: 2022,
    STATE: 'MN',
    RATE: 24.8,
    DEATHS: 1384,
    URL: '/nchs/pressroom/states/minnesota/mn.htm',
  },
  {
    YEAR: 2022,
    STATE: 'MS',
    RATE: 27.6,
    DEATHS: 758,
    URL: '/nchs/pressroom/states/mississippi/ms.htm',
  },
  {
    YEAR: 2022,
    STATE: 'MO',
    RATE: 36.9,
    DEATHS: 2192,
    URL: '/nchs/pressroom/states/missouri/mo.htm',
  },
  {
    YEAR: 2022,
    STATE: 'MT',
    RATE: 19.4,
    DEATHS: 208,
    URL: '/nchs/pressroom/states/montana/mt.htm',
  },
  {
    YEAR: 2022,
    STATE: 'NE',
    RATE: 11.8,
    DEATHS: 225,
    URL: '/nchs/pressroom/states/nebraska/ne.htm',
  },
  {
    YEAR: 2022,
    STATE: 'NV',
    RATE: 30.3,
    DEATHS: 1003,
    URL: '/nchs/pressroom/states/nevada/nv.htm',
  },
  {
    YEAR: 2022,
    STATE: 'NH',
    RATE: 36.0,
    DEATHS: 486,
    URL: '/nchs/pressroom/states/newhampshire/nh.htm',
  },
  {
    YEAR: 2022,
    STATE: 'NJ',
    RATE: 31.6,
    DEATHS: 2985,
    URL: '/nchs/pressroom/states/newjersey/nj.htm',
  },
  {
    YEAR: 2022,
    STATE: 'NM',
    RATE: 50.3,
    DEATHS: 1024,
    URL: '/nchs/pressroom/states/newmexico/nm.htm',
  },
  {
    YEAR: 2022,
    STATE: 'NY',
    RATE: 31.4,
    DEATHS: 6358,
    URL: '/nchs/pressroom/states/newyork/ny.htm',
  },
  {
    YEAR: 2022,
    STATE: 'NC',
    RATE: 41.8,
    DEATHS: 4310,
    URL: '/nchs/pressroom/states/northcarolina/nc.htm',
  },
  {
    YEAR: 2022,
    STATE: 'ND',
    RATE: 19.8,
    DEATHS: 148,
    URL: '/nchs/pressroom/states/northdakota/nd.htm',
  },
  {
    YEAR: 2022,
    STATE: 'OH',
    RATE: 45.6,
    DEATHS: 5144,
    URL: '/nchs/pressroom/states/ohio/oh.htm',
  },
  {
    YEAR: 2022,
    STATE: 'OK',
    RATE: 30.7,
    DEATHS: 1196,
    URL: '/nchs/pressroom/states/oklahoma/ok.htm',
  },
  {
    YEAR: 2022,
    STATE: 'OR',
    RATE: 31.1,
    DEATHS: 1363,
    URL: '/nchs/pressroom/states/oregon/or.htm',
  },
  {
    YEAR: 2022,
    STATE: 'PA',
    RATE: 40.9,
    DEATHS: 5169,
    URL: '/nchs/pressroom/states/pennsylvania/pa.htm',
  },
  {
    YEAR: 2022,
    STATE: 'RI',
    RATE: 38.1,
    DEATHS: 424,
    URL: '/nchs/pressroom/states/rhodeisland/ri.htm',
  },
  {
    YEAR: 2022,
    STATE: 'SC',
    RATE: 44.7,
    DEATHS: 2279,
    URL: '/nchs/pressroom/states/southcarolina/sc.htm',
  },
  {
    YEAR: 2022,
    STATE: 'SD',
    RATE: 11.3,
    DEATHS: 95,
    URL: '/nchs/pressroom/states/southdakota/sd.htm',
  },
  {
    YEAR: 2022,
    STATE: 'TN',
    RATE: 56.0,
    DEATHS: 3825,
    URL: '/nchs/pressroom/states/tennessee/tn.htm',
  },
  {
    YEAR: 2022,
    STATE: 'TX',
    RATE: 18.2,
    DEATHS: 5489,
    URL: '/nchs/pressroom/states/texas/tx.htm',
  },
  {
    YEAR: 2022,
    STATE: 'UT',
    RATE: 19.8,
    DEATHS: 627,
    URL: '/nchs/pressroom/states/utah/ut.htm',
  },
  {
    YEAR: 2022,
    STATE: 'VT',
    RATE: 45.9,
    DEATHS: 276,
    URL: '/nchs/pressroom/states/vermont/vt.htm',
  },
  {
    YEAR: 2022,
    STATE: 'VA',
    RATE: 28.8,
    DEATHS: 2496,
    URL: '/nchs/pressroom/states/virginia/va.htm',
  },
  {
    YEAR: 2022,
    STATE: 'WA',
    RATE: 33.7,
    DEATHS: 2725,
    URL: '/nchs/pressroom/states/washington/wa.htm',
  },
  {
    YEAR: 2022,
    STATE: 'WV',
    RATE: 80.9,
    DEATHS: 1335,
    URL: '/nchs/pressroom/states/westvirginia/wv.htm',
  },
  {
    YEAR: 2022,
    STATE: 'WI',
    RATE: 31.8,
    DEATHS: 1792,
    URL: '/nchs/pressroom/states/wisconsin/wi.htm',
  },
  {
    YEAR: 2022,
    STATE: 'WY',
    RATE: 21.9,
    DEATHS: 126,
    URL: '/nchs/pressroom/states/wyoming/wy.htm',
  },
  {
    YEAR: 2021,
    STATE: 'AL',
    RATE: 30.1,
    DEATHS: 1408,
    URL: '/nchs/pressroom/states/alabama/al.htm',
  },
  {
    YEAR: 2021,
    STATE: 'AK',
    RATE: 35.6,
    DEATHS: 260,
    URL: '/nchs/pressroom/states/alaska/ak.htm',
  },
  {
    YEAR: 2021,
    STATE: 'AZ',
    RATE: 38.7,
    DEATHS: 2730,
    URL: '/nchs/pressroom/states/arizona/az.htm',
  },
  {
    YEAR: 2021,
    STATE: 'AR',
    RATE: 22.3,
    DEATHS: 637,
    URL: '/nchs/pressroom/states/arkansas/ar.htm',
  },
  {
    YEAR: 2021,
    STATE: 'CA',
    RATE: 26.6,
    DEATHS: 10901,
    URL: '/nchs/pressroom/states/california/ca.htm',
  },
  {
    YEAR: 2021,
    STATE: 'CO',
    RATE: 31.4,
    DEATHS: 1887,
    URL: '/nchs/pressroom/states/colorado/co.htm',
  },
  {
    YEAR: 2021,
    STATE: 'CT',
    RATE: 42.3,
    DEATHS: 1552,
    URL: '/nchs/pressroom/states/connecticut/ct.htm',
  },
  {
    YEAR: 2021,
    STATE: 'DE',
    RATE: 54.0,
    DEATHS: 513,
    URL: '/nchs/pressroom/states/delaware/de.htm',
  },
  {
    YEAR: 2021,
    STATE: 'FL',
    RATE: 37.5,
    DEATHS: 7827,
    URL: '/nchs/pressroom/states/florida/fl.htm',
  },
  {
    YEAR: 2021,
    STATE: 'GA',
    RATE: 23.5,
    DEATHS: 2500,
    URL: '/nchs/pressroom/states/georgia/ga.htm',
  },
  {
    YEAR: 2021,
    STATE: 'HI',
    RATE: 17.3,
    DEATHS: 269,
    URL: '/nchs/pressroom/states/hawaii/hi.htm',
  },
  {
    YEAR: 2021,
    STATE: 'ID',
    RATE: 19.0,
    DEATHS: 354,
    URL: '/nchs/pressroom/states/idaho/id.htm',
  },
  {
    YEAR: 2021,
    STATE: 'IL',
    RATE: 29.0,
    DEATHS: 3762,
    URL: '/nchs/pressroom/states/illinois/il.htm',
  },
  {
    YEAR: 2021,
    STATE: 'IN',
    RATE: 43.0,
    DEATHS: 2811,
    URL: '/nchs/pressroom/states/indiana/in.htm',
  },
  {
    YEAR: 2021,
    STATE: 'IA',
    RATE: 15.3,
    DEATHS: 475,
    URL: '/nchs/pressroom/states/iowa/ia.htm',
  },
  {
    YEAR: 2021,
    STATE: 'KS',
    RATE: 24.3,
    DEATHS: 680,
    URL: '/nchs/pressroom/states/kansas/ks.htm',
  },
  {
    YEAR: 2021,
    STATE: 'KY',
    RATE: 55.6,
    DEATHS: 2381,
    URL: '/nchs/pressroom/states/kentucky/ky.htm',
  },
  {
    YEAR: 2021,
    STATE: 'LA',
    RATE: 55.9,
    DEATHS: 2463,
    URL: '/nchs/pressroom/states/louisiana/la.htm',
  },
  {
    YEAR: 2021,
    STATE: 'ME',
    RATE: 47.1,
    DEATHS: 611,
    URL: '/nchs/pressroom/states/maine/me.htm',
  },
  {
    YEAR: 2021,
    STATE: 'MD',
    RATE: 42.8,
    DEATHS: 2737,
    URL: '/nchs/pressroom/states/maryland/md.htm',
  },
  {
    YEAR: 2021,
    STATE: 'MA',
    RATE: 36.8,
    DEATHS: 2585,
    URL: '/nchs/pressroom/states/massachusetts/ma.htm',
  },
  {
    YEAR: 2021,
    STATE: 'MI',
    RATE: 31.5,
    DEATHS: 3089,
    URL: '/nchs/pressroom/states/michigan/mi.htm',
  },
  {
    YEAR: 2021,
    STATE: 'MN',
    RATE: 24.5,
    DEATHS: 1356,
    URL: '/nchs/pressroom/states/minnesota/mn.htm',
  },
  {
    YEAR: 2021,
    STATE: 'MS',
    RATE: 28.4,
    DEATHS: 787,
    URL: '/nchs/pressroom/states/mississippi/ms.htm',
  },
  {
    YEAR: 2021,
    STATE: 'MO',
    RATE: 36.5,
    DEATHS: 2155,
    URL: '/nchs/pressroom/states/missouri/mo.htm',
  },
  {
    YEAR: 2021,
    STATE: 'MT',
    RATE: 19.5,
    DEATHS: 199,
    URL: '/nchs/pressroom/states/montana/mt.htm',
  },
  {
    YEAR: 2021,
    STATE: 'NE',
    RATE: 11.4,
    DEATHS: 214,
    URL: '/nchs/pressroom/states/nebraska/ne.htm',
  },
  {
    YEAR: 2021,
    STATE: 'NV',
    RATE: 29.2,
    DEATHS: 949,
    URL: '/nchs/pressroom/states/nevada/nv.htm',
  },
  {
    YEAR: 2021,
    STATE: 'NH',
    RATE: 32.3,
    DEATHS: 441,
    URL: '/nchs/pressroom/states/newhampshire/nh.htm',
  },
  {
    YEAR: 2021,
    STATE: 'NJ',
    RATE: 32.4,
    DEATHS: 3056,
    URL: '/nchs/pressroom/states/newjersey/nj.htm',
  },
  {
    YEAR: 2021,
    STATE: 'NM',
    RATE: 51.6,
    DEATHS: 1052,
    URL: '/nchs/pressroom/states/newmexico/nm.htm',
  },
  {
    YEAR: 2021,
    STATE: 'NY',
    RATE: 28.7,
    DEATHS: 5842,
    URL: '/nchs/pressroom/states/newyork/ny.htm',
  },
  {
    YEAR: 2021,
    STATE: 'NC',
    RATE: 39.2,
    DEATHS: 3981,
    URL: '/nchs/pressroom/states/northcarolina/nc.htm',
  },
  {
    YEAR: 2021,
    STATE: 'ND',
    RATE: 17.2,
    DEATHS: 124,
    URL: '/nchs/pressroom/states/northdakota/nd.htm',
  },
  {
    YEAR: 2021,
    STATE: 'OH',
    RATE: 48.1,
    DEATHS: 5397,
    URL: '/nchs/pressroom/states/ohio/oh.htm',
  },
  {
    YEAR: 2021,
    STATE: 'OK',
    RATE: 24.4,
    DEATHS: 960,
    URL: '/nchs/pressroom/states/oklahoma/ok.htm',
  },
  {
    YEAR: 2021,
    STATE: 'OR',
    RATE: 26.8,
    DEATHS: 1171,
    URL: '/nchs/pressroom/states/oregon/or.htm',
  },
  {
    YEAR: 2021,
    STATE: 'PA',
    RATE: 43.2,
    DEATHS: 5449,
    URL: '/nchs/pressroom/states/pennsylvania/pa.htm',
  },
  {
    YEAR: 2021,
    STATE: 'RI',
    RATE: 41.7,
    DEATHS: 455,
    URL: '/nchs/pressroom/states/rhodeisland/ri.htm',
  },
  {
    YEAR: 2021,
    STATE: 'SC',
    RATE: 42.8,
    DEATHS: 2138,
    URL: '/nchs/pressroom/states/southcarolina/sc.htm',
  },
  {
    YEAR: 2021,
    STATE: 'SD',
    RATE: 12.6,
    DEATHS: 105,
    URL: '/nchs/pressroom/states/southdakota/sd.htm',
  },
  {
    YEAR: 2021,
    STATE: 'TN',
    RATE: 56.6,
    DEATHS: 3813,
    URL: '/nchs/pressroom/states/tennessee/tn.htm',
  },
  {
    YEAR: 2021,
    STATE: 'TX',
    RATE: 16.8,
    DEATHS: 4984,
    URL: '/nchs/pressroom/states/texas/tx.htm',
  },
  {
    YEAR: 2021,
    STATE: 'UT',
    RATE: 21.1,
    DEATHS: 662,
    URL: '/nchs/pressroom/states/utah/ut.htm',
  },
  {
    YEAR: 2021,
    STATE: 'VT',
    RATE: 42.3,
    DEATHS: 252,
    URL: '/nchs/pressroom/states/vermont/vt.htm',
  },
  {
    YEAR: 2021,
    STATE: 'VA',
    RATE: 30.5,
    DEATHS: 2626,
    URL: '/nchs/pressroom/states/virginia/va.htm',
  },
  {
    YEAR: 2021,
    STATE: 'WA',
    RATE: 28.1,
    DEATHS: 2264,
    URL: '/nchs/pressroom/states/washington/wa.htm',
  },
  {
    YEAR: 2021,
    STATE: 'WV',
    RATE: 90.9,
    DEATHS: 1501,
    URL: '/nchs/pressroom/states/westvirginia/wv.htm',
  },
  {
    YEAR: 2021,
    STATE: 'WI',
    RATE: 31.6,
    DEATHS: 1775,
    URL: '/nchs/pressroom/states/wisconsin/wi.htm',
  },
  {
    YEAR: 2021,
    STATE: 'WY',
    RATE: 18.9,
    DEATHS: 109,
    URL: '/nchs/pressroom/states/wyoming/wy.htm',
  },
  {
    YEAR: 2020,
    STATE: 'AL',
    RATE: 22.3,
    DEATHS: 1029,
    URL: '/nchs/pressroom/states/alabama/al.htm',
  },
  {
    YEAR: 2020,
    STATE: 'AK',
    RATE: 22.0,
    DEATHS: 160,
    URL: '/nchs/pressroom/states/alaska/ak.htm',
  },
  {
    YEAR: 2020,
    STATE: 'AZ',
    RATE: 35.8,
    DEATHS: 2550,
    URL: '/nchs/pressroom/states/arizona/az.htm',
  },
  {
    YEAR: 2020,
    STATE: 'AR',
    RATE: 19.1,
    DEATHS: 546,
    URL: '/nchs/pressroom/states/arkansas/ar.htm',
  },
  {
    YEAR: 2020,
    STATE: 'CA',
    RATE: 21.8,
    DEATHS: 8908,
    URL: '/nchs/pressroom/states/california/ca.htm',
  },
  {
    YEAR: 2020,
    STATE: 'CO',
    RATE: 24.9,
    DEATHS: 1492,
    URL: '/nchs/pressroom/states/colorado/co.htm',
  },
  {
    YEAR: 2020,
    STATE: 'CT',
    RATE: 39.1,
    DEATHS: 1371,
    URL: '/nchs/pressroom/states/connecticut/ct.htm',
  },
  {
    YEAR: 2020,
    STATE: 'DE',
    RATE: 47.3,
    DEATHS: 444,
    URL: '/nchs/pressroom/states/delaware/de.htm',
  },
  {
    YEAR: 2020,
    STATE: 'FL',
    RATE: 35.0,
    DEATHS: 7231,
    URL: '/nchs/pressroom/states/florida/fl.htm',
  },
  {
    YEAR: 2020,
    STATE: 'GA',
    RATE: 18.0,
    DEATHS: 1916,
    URL: '/nchs/pressroom/states/georgia/ga.htm',
  },
  {
    YEAR: 2020,
    STATE: 'HI',
    RATE: 18.3,
    DEATHS: 274,
    URL: '/nchs/pressroom/states/hawaii/hi.htm',
  },
  {
    YEAR: 2020,
    STATE: 'ID',
    RATE: 15.9,
    DEATHS: 287,
    URL: '/nchs/pressroom/states/idaho/id.htm',
  },
  {
    YEAR: 2020,
    STATE: 'IL',
    RATE: 28.1,
    DEATHS: 3549,
    URL: '/nchs/pressroom/states/illinois/il.htm',
  },
  {
    YEAR: 2020,
    STATE: 'IN',
    RATE: 36.7,
    DEATHS: 2321,
    URL: '/nchs/pressroom/states/indiana/in.htm',
  },
  {
    YEAR: 2020,
    STATE: 'IA',
    RATE: 14.3,
    DEATHS: 432,
    URL: '/nchs/pressroom/states/iowa/ia.htm',
  },
  {
    YEAR: 2020,
    STATE: 'KS',
    RATE: 17.4,
    DEATHS: 490,
    URL: '/nchs/pressroom/states/kansas/ks.htm',
  },
  {
    YEAR: 2020,
    STATE: 'KY',
    RATE: 49.2,
    DEATHS: 2083,
    URL: '/nchs/pressroom/states/kentucky/ky.htm',
  },
  {
    YEAR: 2020,
    STATE: 'LA',
    RATE: 42.7,
    DEATHS: 1896,
    URL: '/nchs/pressroom/states/louisiana/la.htm',
  },
  {
    YEAR: 2020,
    STATE: 'ME',
    RATE: 39.7,
    DEATHS: 496,
    URL: '/nchs/pressroom/states/maine/me.htm',
  },
  {
    YEAR: 2020,
    STATE: 'MD',
    RATE: 44.6,
    DEATHS: 2771,
    URL: '/nchs/pressroom/states/maryland/md.htm',
  },
  {
    YEAR: 2020,
    STATE: 'MA',
    RATE: 33.9,
    DEATHS: 2302,
    URL: '/nchs/pressroom/states/massachusetts/ma.htm',
  },
  {
    YEAR: 2020,
    STATE: 'MI',
    RATE: 28.6,
    DEATHS: 2759,
    URL: '/nchs/pressroom/states/michigan/mi.htm',
  },
  {
    YEAR: 2020,
    STATE: 'MN',
    RATE: 19.0,
    DEATHS: 1050,
    URL: '/nchs/pressroom/states/minnesota/mn.htm',
  },
  {
    YEAR: 2020,
    STATE: 'MS',
    RATE: 21.1,
    DEATHS: 586,
    URL: '/nchs/pressroom/states/mississippi/ms.htm',
  },
  {
    YEAR: 2020,
    STATE: 'MO',
    RATE: 32.1,
    DEATHS: 1875,
    URL: '/nchs/pressroom/states/missouri/mo.htm',
  },
  {
    YEAR: 2020,
    STATE: 'MT',
    RATE: 15.6,
    DEATHS: 162,
    URL: '/nchs/pressroom/states/montana/mt.htm',
  },
  {
    YEAR: 2020,
    STATE: 'NE',
    RATE: 11.3,
    DEATHS: 214,
    URL: '/nchs/pressroom/states/nebraska/ne.htm',
  },
  {
    YEAR: 2020,
    STATE: 'NV',
    RATE: 26.0,
    DEATHS: 832,
    URL: '/nchs/pressroom/states/nevada/nv.htm',
  },
  {
    YEAR: 2020,
    STATE: 'NH',
    RATE: 30.3,
    DEATHS: 393,
    URL: '/nchs/pressroom/states/newhampshire/nh.htm',
  },
  {
    YEAR: 2020,
    STATE: 'NJ',
    RATE: 32.1,
    DEATHS: 2840,
    URL: '/nchs/pressroom/states/newjersey/nj.htm',
  },
  {
    YEAR: 2020,
    STATE: 'NM',
    RATE: 39.0,
    DEATHS: 784,
    URL: '/nchs/pressroom/states/newmexico/nm.htm',
  },
  {
    YEAR: 2020,
    STATE: 'NY',
    RATE: 25.4,
    DEATHS: 4965,
    URL: '/nchs/pressroom/states/newyork/ny.htm',
  },
  {
    YEAR: 2020,
    STATE: 'NC',
    RATE: 30.9,
    DEATHS: 3146,
    URL: '/nchs/pressroom/states/northcarolina/nc.htm',
  },
  {
    YEAR: 2020,
    STATE: 'ND',
    RATE: 15.6,
    DEATHS: 114,
    URL: '/nchs/pressroom/states/northdakota/nd.htm',
  },
  {
    YEAR: 2020,
    STATE: 'OH',
    RATE: 47.2,
    DEATHS: 5204,
    URL: '/nchs/pressroom/states/ohio/oh.htm',
  },
  {
    YEAR: 2020,
    STATE: 'OK',
    RATE: 19.4,
    DEATHS: 762,
    URL: '/nchs/pressroom/states/oklahoma/ok.htm',
  },
  {
    YEAR: 2020,
    STATE: 'OR',
    RATE: 18.7,
    DEATHS: 803,
    URL: '/nchs/pressroom/states/oregon/or.htm',
  },
  {
    YEAR: 2020,
    STATE: 'PA',
    RATE: 42.4,
    DEATHS: 5168,
    URL: '/nchs/pressroom/states/pennsylvania/pa.htm',
  },
  {
    YEAR: 2020,
    STATE: 'RI',
    RATE: 38.2,
    DEATHS: 397,
    URL: '/nchs/pressroom/states/rhodeisland/ri.htm',
  },
  {
    YEAR: 2020,
    STATE: 'SC',
    RATE: 34.9,
    DEATHS: 1739,
    URL: '/nchs/pressroom/states/southcarolina/sc.htm',
  },
  {
    YEAR: 2020,
    STATE: 'SD',
    RATE: 10.3,
    DEATHS: 83,
    URL: '/nchs/pressroom/states/southdakota/sd.htm',
  },
  {
    YEAR: 2020,
    STATE: 'TN',
    RATE: 45.6,
    DEATHS: 3034,
    URL: '/nchs/pressroom/states/tennessee/tn.htm',
  },
  {
    YEAR: 2020,
    STATE: 'TX',
    RATE: 14.1,
    DEATHS: 4172,
    URL: '/nchs/pressroom/states/texas/tx.htm',
  },
  {
    YEAR: 2020,
    STATE: 'UT',
    RATE: 20.5,
    DEATHS: 622,
    URL: '/nchs/pressroom/states/utah/ut.htm',
  },
  {
    YEAR: 2020,
    STATE: 'VT',
    RATE: 32.9,
    DEATHS: 190,
    URL: '/nchs/pressroom/states/vermont/vt.htm',
  },
  {
    YEAR: 2020,
    STATE: 'VA',
    RATE: 26.6,
    DEATHS: 2240,
    URL: '/nchs/pressroom/states/virginia/va.htm',
  },
  {
    YEAR: 2020,
    STATE: 'WA',
    RATE: 22.0,
    DEATHS: 1733,
    URL: '/nchs/pressroom/states/washington/wa.htm',
  },
  {
    YEAR: 2020,
    STATE: 'WV',
    RATE: 81.4,
    DEATHS: 1330,
    URL: '/nchs/pressroom/states/westvirginia/wv.htm',
  },
  {
    YEAR: 2020,
    STATE: 'WI',
    RATE: 27.7,
    DEATHS: 1531,
    URL: '/nchs/pressroom/states/wisconsin/wi.htm',
  },
  {
    YEAR: 2020,
    STATE: 'WY',
    RATE: 17.4,
    DEATHS: 99,
    URL: '/nchs/pressroom/states/wyoming/wy.htm',
  },
  {
    YEAR: 2019,
    STATE: 'AL',
    RATE: 16.3,
    DEATHS: 768,
    URL: '/nchs/pressroom/states/alabama/al.htm',
  },
  {
    YEAR: 2019,
    STATE: 'AK',
    RATE: 17.8,
    DEATHS: 132,
    URL: '/nchs/pressroom/states/alaska/ak.htm',
  },
  {
    YEAR: 2019,
    STATE: 'AZ',
    RATE: 26.8,
    DEATHS: 1907,
    URL: '/nchs/pressroom/states/arizona/az.htm',
  },
  {
    YEAR: 2019,
    STATE: 'AR',
    RATE: 13.5,
    DEATHS: 388,
    URL: '/nchs/pressroom/states/arkansas/ar.htm',
  },
  {
    YEAR: 2019,
    STATE: 'CA',
    RATE: 15.0,
    DEATHS: 6198,
    URL: '/nchs/pressroom/states/california/ca.htm',
  },
  {
    YEAR: 2019,
    STATE: 'CO',
    RATE: 18.0,
    DEATHS: 1079,
    URL: '/nchs/pressroom/states/colorado/co.htm',
  },
  {
    YEAR: 2019,
    STATE: 'CT',
    RATE: 34.7,
    DEATHS: 1214,
    URL: '/nchs/pressroom/states/connecticut/ct.htm',
  },
  {
    YEAR: 2019,
    STATE: 'DE',
    RATE: 48.0,
    DEATHS: 435,
    URL: '/nchs/pressroom/states/delaware/de.htm',
  },
  {
    YEAR: 2019,
    STATE: 'FL',
    RATE: 25.5,
    DEATHS: 5268,
    URL: '/nchs/pressroom/states/florida/fl.htm',
  },
  {
    YEAR: 2019,
    STATE: 'GA',
    RATE: 13.1,
    DEATHS: 1408,
    URL: '/nchs/pressroom/states/georgia/ga.htm',
  },
  {
    YEAR: 2019,
    STATE: 'HI',
    RATE: 15.9,
    DEATHS: 242,
    URL: '/nchs/pressroom/states/hawaii/hi.htm',
  },
  {
    YEAR: 2019,
    STATE: 'ID',
    RATE: 15.1,
    DEATHS: 265,
    URL: '/nchs/pressroom/states/idaho/id.htm',
  },
  {
    YEAR: 2019,
    STATE: 'IL',
    RATE: 21.9,
    DEATHS: 2790,
    URL: '/nchs/pressroom/states/illinois/il.htm',
  },
  {
    YEAR: 2019,
    STATE: 'IN',
    RATE: 26.6,
    DEATHS: 1699,
    URL: '/nchs/pressroom/states/indiana/in.htm',
  },
  {
    YEAR: 2019,
    STATE: 'IA',
    RATE: 11.5,
    DEATHS: 352,
    URL: '/nchs/pressroom/states/iowa/ia.htm',
  },
  {
    YEAR: 2019,
    STATE: 'KS',
    RATE: 14.3,
    DEATHS: 403,
    URL: '/nchs/pressroom/states/kansas/ks.htm',
  },
  {
    YEAR: 2019,
    STATE: 'KY',
    RATE: 32.5,
    DEATHS: 1380,
    URL: '/nchs/pressroom/states/kentucky/ky.htm',
  },
  {
    YEAR: 2019,
    STATE: 'LA',
    RATE: 28.3,
    DEATHS: 1267,
    URL: '/nchs/pressroom/states/louisiana/la.htm',
  },
  {
    YEAR: 2019,
    STATE: 'ME',
    RATE: 29.9,
    DEATHS: 371,
    URL: '/nchs/pressroom/states/maine/me.htm',
  },
  {
    YEAR: 2019,
    STATE: 'MD',
    RATE: 38.2,
    DEATHS: 2369,
    URL: '/nchs/pressroom/states/maryland/md.htm',
  },
  {
    YEAR: 2019,
    STATE: 'MA',
    RATE: 32.1,
    DEATHS: 2210,
    URL: '/nchs/pressroom/states/massachusetts/ma.htm',
  },
  {
    YEAR: 2019,
    STATE: 'MI',
    RATE: 24.4,
    DEATHS: 2385,
    URL: '/nchs/pressroom/states/michigan/mi.htm',
  },
  {
    YEAR: 2019,
    STATE: 'MN',
    RATE: 14.2,
    DEATHS: 792,
    URL: '/nchs/pressroom/states/minnesota/mn.htm',
  },
  {
    YEAR: 2019,
    STATE: 'MS',
    RATE: 13.6,
    DEATHS: 394,
    URL: '/nchs/pressroom/states/mississippi/ms.htm',
  },
  {
    YEAR: 2019,
    STATE: 'MO',
    RATE: 26.9,
    DEATHS: 1583,
    URL: '/nchs/pressroom/states/missouri/mo.htm',
  },
  {
    YEAR: 2019,
    STATE: 'MT',
    RATE: 14.1,
    DEATHS: 143,
    URL: '/nchs/pressroom/states/montana/mt.htm',
  },
  {
    YEAR: 2019,
    STATE: 'NE',
    RATE: 8.7,
    DEATHS: 161,
    URL: '/nchs/pressroom/states/nebraska/ne.htm',
  },
  {
    YEAR: 2019,
    STATE: 'NV',
    RATE: 20.1,
    DEATHS: 647,
    URL: '/nchs/pressroom/states/nevada/nv.htm',
  },
  {
    YEAR: 2019,
    STATE: 'NH',
    RATE: 32.0,
    DEATHS: 407,
    URL: '/nchs/pressroom/states/newhampshire/nh.htm',
  },
  {
    YEAR: 2019,
    STATE: 'NJ',
    RATE: 31.7,
    DEATHS: 2805,
    URL: '/nchs/pressroom/states/newjersey/nj.htm',
  },
  {
    YEAR: 2019,
    STATE: 'NM',
    RATE: 30.2,
    DEATHS: 599,
    URL: '/nchs/pressroom/states/newmexico/nm.htm',
  },
  {
    YEAR: 2019,
    STATE: 'NY',
    RATE: 18.2,
    DEATHS: 3617,
    URL: '/nchs/pressroom/states/newyork/ny.htm',
  },
  {
    YEAR: 2019,
    STATE: 'NC',
    RATE: 22.3,
    DEATHS: 2266,
    URL: '/nchs/pressroom/states/northcarolina/nc.htm',
  },
  {
    YEAR: 2019,
    STATE: 'ND',
    RATE: 11.4,
    DEATHS: 82,
    URL: '/nchs/pressroom/states/northdakota/nd.htm',
  },
  {
    YEAR: 2019,
    STATE: 'OH',
    RATE: 38.3,
    DEATHS: 4251,
    URL: '/nchs/pressroom/states/ohio/oh.htm',
  },
  {
    YEAR: 2019,
    STATE: 'OK',
    RATE: 16.7,
    DEATHS: 645,
    URL: '/nchs/pressroom/states/oklahoma/ok.htm',
  },
  {
    YEAR: 2019,
    STATE: 'OR',
    RATE: 14.0,
    DEATHS: 615,
    URL: '/nchs/pressroom/states/oregon/or.htm',
  },
  {
    YEAR: 2019,
    STATE: 'PA',
    RATE: 35.6,
    DEATHS: 4377,
    URL: '/nchs/pressroom/states/pennsylvania/pa.htm',
  },
  {
    YEAR: 2019,
    STATE: 'RI',
    RATE: 29.5,
    DEATHS: 307,
    URL: '/nchs/pressroom/states/rhodeisland/ri.htm',
  },
  {
    YEAR: 2019,
    STATE: 'SC',
    RATE: 22.7,
    DEATHS: 1127,
    URL: '/nchs/pressroom/states/southcarolina/sc.htm',
  },
  {
    YEAR: 2019,
    STATE: 'SD',
    RATE: 10.5,
    DEATHS: 86,
    URL: '/nchs/pressroom/states/southdakota/sd.htm',
  },
  {
    YEAR: 2019,
    STATE: 'TN',
    RATE: 31.2,
    DEATHS: 2089,
    URL: '/nchs/pressroom/states/tennessee/tn.htm',
  },
  {
    YEAR: 2019,
    STATE: 'TX',
    RATE: 10.8,
    DEATHS: 3136,
    URL: '/nchs/pressroom/states/texas/tx.htm',
  },
  {
    YEAR: 2019,
    STATE: 'UT',
    RATE: 18.9,
    DEATHS: 571,
    URL: '/nchs/pressroom/states/utah/ut.htm',
  },
  {
    YEAR: 2019,
    STATE: 'VT',
    RATE: 23.8,
    DEATHS: 133,
    URL: '/nchs/pressroom/states/vermont/vt.htm',
  },
  {
    YEAR: 2019,
    STATE: 'VA',
    RATE: 18.3,
    DEATHS: 1547,
    URL: '/nchs/pressroom/states/virginia/va.htm',
  },
  {
    YEAR: 2019,
    STATE: 'WA',
    RATE: 15.8,
    DEATHS: 1259,
    URL: '/nchs/pressroom/states/washington/wa.htm',
  },
  {
    YEAR: 2019,
    STATE: 'WV',
    RATE: 52.8,
    DEATHS: 870,
    URL: '/nchs/pressroom/states/westvirginia/wv.htm',
  },
  {
    YEAR: 2019,
    STATE: 'WI',
    RATE: 21.1,
    DEATHS: 1201,
    URL: '/nchs/pressroom/states/wisconsin/wi.htm',
  },
  {
    YEAR: 2019,
    STATE: 'WY',
    RATE: 14.1,
    DEATHS: 79,
    URL: '/nchs/pressroom/states/wyoming/wy.htm',
  },
  {
    YEAR: 2018,
    STATE: 'AL',
    RATE: 16.6,
    DEATHS: 775,
    URL: '/nchs/pressroom/states/alabama/al.htm',
  },
  {
    YEAR: 2018,
    STATE: 'AK',
    RATE: 14.6,
    DEATHS: 110,
    URL: '/nchs/pressroom/states/alaska/ak.htm',
  },
  {
    YEAR: 2018,
    STATE: 'AZ',
    RATE: 23.8,
    DEATHS: 1670,
    URL: '/nchs/pressroom/states/arizona/az.htm',
  },
  {
    YEAR: 2018,
    STATE: 'AR',
    RATE: 15.7,
    DEATHS: 444,
    URL: '/nchs/pressroom/states/arkansas/ar.htm',
  },
  {
    YEAR: 2018,
    STATE: 'CA',
    RATE: 12.8,
    DEATHS: 5348,
    URL: '/nchs/pressroom/states/california/ca.htm',
  },
  {
    YEAR: 2018,
    STATE: 'CO',
    RATE: 16.8,
    DEATHS: 995,
    URL: '/nchs/pressroom/states/colorado/co.htm',
  },
  {
    YEAR: 2018,
    STATE: 'CT',
    RATE: 30.7,
    DEATHS: 1069,
    URL: '/nchs/pressroom/states/connecticut/ct.htm',
  },
  {
    YEAR: 2018,
    STATE: 'DE',
    RATE: 43.8,
    DEATHS: 401,
    URL: '/nchs/pressroom/states/delaware/de.htm',
  },
  {
    YEAR: 2018,
    STATE: 'FL',
    RATE: 22.8,
    DEATHS: 4698,
    URL: '/nchs/pressroom/states/florida/fl.htm',
  },
  {
    YEAR: 2018,
    STATE: 'GA',
    RATE: 13.2,
    DEATHS: 1404,
    URL: '/nchs/pressroom/states/georgia/ga.htm',
  },
  {
    YEAR: 2018,
    STATE: 'HI',
    RATE: 14.3,
    DEATHS: 213,
    URL: '/nchs/pressroom/states/hawaii/hi.htm',
  },
  {
    YEAR: 2018,
    STATE: 'ID',
    RATE: 14.6,
    DEATHS: 250,
    URL: '/nchs/pressroom/states/idaho/id.htm',
  },
  {
    YEAR: 2018,
    STATE: 'IL',
    RATE: 21.3,
    DEATHS: 2722,
    URL: '/nchs/pressroom/states/illinois/il.htm',
  },
  {
    YEAR: 2018,
    STATE: 'IN',
    RATE: 25.6,
    DEATHS: 1629,
    URL: '/nchs/pressroom/states/indiana/in.htm',
  },
  {
    YEAR: 2018,
    STATE: 'IA',
    RATE: 9.6,
    DEATHS: 287,
    URL: '/nchs/pressroom/states/iowa/ia.htm',
  },
  {
    YEAR: 2018,
    STATE: 'KS',
    RATE: 12.4,
    DEATHS: 345,
    URL: '/nchs/pressroom/states/kansas/ks.htm',
  },
  {
    YEAR: 2018,
    STATE: 'KY',
    RATE: 30.9,
    DEATHS: 1315,
    URL: '/nchs/pressroom/states/kentucky/ky.htm',
  },
  {
    YEAR: 2018,
    STATE: 'LA',
    RATE: 25.4,
    DEATHS: 1140,
    URL: '/nchs/pressroom/states/louisiana/la.htm',
  },
  {
    YEAR: 2018,
    STATE: 'ME',
    RATE: 27.9,
    DEATHS: 345,
    URL: '/nchs/pressroom/states/maine/me.htm',
  },
  {
    YEAR: 2018,
    STATE: 'MD',
    RATE: 37.2,
    DEATHS: 2324,
    URL: '/nchs/pressroom/states/maryland/md.htm',
  },
  {
    YEAR: 2018,
    STATE: 'MA',
    RATE: 32.8,
    DEATHS: 2241,
    URL: '/nchs/pressroom/states/massachusetts/ma.htm',
  },
  {
    YEAR: 2018,
    STATE: 'MI',
    RATE: 26.6,
    DEATHS: 2591,
    URL: '/nchs/pressroom/states/michigan/mi.htm',
  },
  {
    YEAR: 2018,
    STATE: 'MN',
    RATE: 11.5,
    DEATHS: 636,
    URL: '/nchs/pressroom/states/minnesota/mn.htm',
  },
  {
    YEAR: 2018,
    STATE: 'MS',
    RATE: 10.8,
    DEATHS: 310,
    URL: '/nchs/pressroom/states/mississippi/ms.htm',
  },
  {
    YEAR: 2018,
    STATE: 'MO',
    RATE: 27.5,
    DEATHS: 1610,
    URL: '/nchs/pressroom/states/missouri/mo.htm',
  },
  {
    YEAR: 2018,
    STATE: 'MT',
    RATE: 12.2,
    DEATHS: 125,
    URL: '/nchs/pressroom/states/montana/mt.htm',
  },
  {
    YEAR: 2018,
    STATE: 'NE',
    RATE: 7.4,
    DEATHS: 138,
    URL: '/nchs/pressroom/states/nebraska/ne.htm',
  },
  {
    YEAR: 2018,
    STATE: 'NV',
    RATE: 21.2,
    DEATHS: 688,
    URL: '/nchs/pressroom/states/nevada/nv.htm',
  },
  {
    YEAR: 2018,
    STATE: 'NH',
    RATE: 35.8,
    DEATHS: 452,
    URL: '/nchs/pressroom/states/newhampshire/nh.htm',
  },
  {
    YEAR: 2018,
    STATE: 'NJ',
    RATE: 33.1,
    DEATHS: 2900,
    URL: '/nchs/pressroom/states/newjersey/nj.htm',
  },
  {
    YEAR: 2018,
    STATE: 'NM',
    RATE: 26.7,
    DEATHS: 537,
    URL: '/nchs/pressroom/states/newmexico/nm.htm',
  },
  {
    YEAR: 2018,
    STATE: 'NY',
    RATE: 18.4,
    DEATHS: 3697,
    URL: '/nchs/pressroom/states/newyork/ny.htm',
  },
  {
    YEAR: 2018,
    STATE: 'NC',
    RATE: 22.4,
    DEATHS: 2259,
    URL: '/nchs/pressroom/states/northcarolina/nc.htm',
  },
  {
    YEAR: 2018,
    STATE: 'ND',
    RATE: 10.2,
    DEATHS: 70,
    URL: '/nchs/pressroom/states/northdakota/nd.htm',
  },
  {
    YEAR: 2018,
    STATE: 'OH',
    RATE: 35.9,
    DEATHS: 3980,
    URL: '/nchs/pressroom/states/ohio/oh.htm',
  },
  {
    YEAR: 2018,
    STATE: 'OK',
    RATE: 18.4,
    DEATHS: 716,
    URL: '/nchs/pressroom/states/oklahoma/ok.htm',
  },
  {
    YEAR: 2018,
    STATE: 'OR',
    RATE: 12.6,
    DEATHS: 547,
    URL: '/nchs/pressroom/states/oregon/or.htm',
  },
  {
    YEAR: 2018,
    STATE: 'PA',
    RATE: 36.1,
    DEATHS: 4415,
    URL: '/nchs/pressroom/states/pennsylvania/pa.htm',
  },
  {
    YEAR: 2018,
    STATE: 'RI',
    RATE: 30.1,
    DEATHS: 317,
    URL: '/nchs/pressroom/states/rhodeisland/ri.htm',
  },
  {
    YEAR: 2018,
    STATE: 'SC',
    RATE: 22.6,
    DEATHS: 1125,
    URL: '/nchs/pressroom/states/southcarolina/sc.htm',
  },
  {
    YEAR: 2018,
    STATE: 'SD',
    RATE: 6.9,
    DEATHS: 57,
    URL: '/nchs/pressroom/states/southdakota/sd.htm',
  },
  {
    YEAR: 2018,
    STATE: 'TN',
    RATE: 27.5,
    DEATHS: 1823,
    URL: '/nchs/pressroom/states/tennessee/tn.htm',
  },
  {
    YEAR: 2018,
    STATE: 'TX',
    RATE: 10.4,
    DEATHS: 3005,
    URL: '/nchs/pressroom/states/texas/tx.htm',
  },
  {
    YEAR: 2018,
    STATE: 'UT',
    RATE: 21.2,
    DEATHS: 624,
    URL: '/nchs/pressroom/states/utah/ut.htm',
  },
  {
    YEAR: 2018,
    STATE: 'VT',
    RATE: 26.6,
    DEATHS: 153,
    URL: '/nchs/pressroom/states/vermont/vt.htm',
  },
  {
    YEAR: 2018,
    STATE: 'VA',
    RATE: 17.1,
    DEATHS: 1448,
    URL: '/nchs/pressroom/states/virginia/va.htm',
  },
  {
    YEAR: 2018,
    STATE: 'WA',
    RATE: 14.8,
    DEATHS: 1164,
    URL: '/nchs/pressroom/states/washington/wa.htm',
  },
  {
    YEAR: 2018,
    STATE: 'WV',
    RATE: 51.5,
    DEATHS: 856,
    URL: '/nchs/pressroom/states/westvirginia/wv.htm',
  },
  {
    YEAR: 2018,
    STATE: 'WI',
    RATE: 19.2,
    DEATHS: 1079,
    URL: '/nchs/pressroom/states/wisconsin/wi.htm',
  },
  {
    YEAR: 2018,
    STATE: 'WY',
    RATE: 11.1,
    DEATHS: 66,
    URL: '/nchs/pressroom/states/wyoming/wy.htm',
  },
  {
    YEAR: 2017,
    STATE: 'AL',
    RATE: 18.0,
    DEATHS: 835,
    URL: '/nchs/pressroom/states/alabama/alabama.htm',
  },
  {
    YEAR: 2017,
    STATE: 'AK',
    RATE: 20.2,
    DEATHS: 147,
    URL: '/nchs/pressroom/states/alaska/alaska.htm',
  },
  {
    YEAR: 2017,
    STATE: 'AZ',
    RATE: 22.2,
    DEATHS: 1532,
    URL: '/nchs/pressroom/states/arizona/arizona.htm',
  },
  {
    YEAR: 2017,
    STATE: 'AR',
    RATE: 15.5,
    DEATHS: 446,
    URL: '/nchs/pressroom/states/arkansas/arkansas.htm',
  },
  {
    YEAR: 2017,
    STATE: 'CA',
    RATE: 11.7,
    DEATHS: 4868,
    URL: '/nchs/pressroom/states/california/california.htm',
  },
  {
    YEAR: 2017,
    STATE: 'CO',
    RATE: 17.6,
    DEATHS: 1015,
    URL: '/nchs/pressroom/states/colorado/colorado.htm',
  },
  {
    YEAR: 2017,
    STATE: 'CT',
    RATE: 30.9,
    DEATHS: 1072,
    URL: '/nchs/pressroom/states/connecticut/connecticut.htm',
  },
  {
    YEAR: 2017,
    STATE: 'DE',
    RATE: 37.0,
    DEATHS: 338,
    URL: '/nchs/pressroom/states/delaware/delaware.htm',
  },
  {
    YEAR: 2017,
    STATE: 'FL',
    RATE: 25.1,
    DEATHS: 5088,
    URL: '/nchs/pressroom/states/florida/florida.htm',
  },
  {
    YEAR: 2017,
    STATE: 'GA',
    RATE: 14.7,
    DEATHS: 1537,
    URL: '/nchs/pressroom/states/georgia/georgia.htm',
  },
  {
    YEAR: 2017,
    STATE: 'HI',
    RATE: 13.8,
    DEATHS: 203,
    URL: '/nchs/pressroom/states/hawaii/hawaii.htm',
  },
  {
    YEAR: 2017,
    STATE: 'ID',
    RATE: 14.4,
    DEATHS: 236,
    URL: '/nchs/pressroom/states/idaho/idaho.htm',
  },
  {
    YEAR: 2017,
    STATE: 'IL',
    RATE: 21.6,
    DEATHS: 2778,
    URL: '/nchs/pressroom/states/illinois/illinois.htm',
  },
  {
    YEAR: 2017,
    STATE: 'IN',
    RATE: 29.4,
    DEATHS: 1852,
    URL: '/nchs/pressroom/states/indiana/indiana.htm',
  },
  {
    YEAR: 2017,
    STATE: 'IA',
    RATE: 11.5,
    DEATHS: 341,
    URL: '/nchs/pressroom/states/iowa/iowa.htm',
  },
  {
    YEAR: 2017,
    STATE: 'KS',
    RATE: 11.8,
    DEATHS: 333,
    URL: '/nchs/pressroom/states/kansas/kansas.htm',
  },
  {
    YEAR: 2017,
    STATE: 'KY',
    RATE: 37.2,
    DEATHS: 1566,
    URL: '/nchs/pressroom/states/kentucky/kentucky.htm',
  },
  {
    YEAR: 2017,
    STATE: 'LA',
    RATE: 24.5,
    DEATHS: 1108,
    URL: '/nchs/pressroom/states/louisiana/louisiana.htm',
  },
  {
    YEAR: 2017,
    STATE: 'ME',
    RATE: 34.4,
    DEATHS: 424,
    URL: '/nchs/pressroom/states/maine/maine.htm',
  },
  {
    YEAR: 2017,
    STATE: 'MD',
    RATE: 36.3,
    DEATHS: 2247,
    URL: '/nchs/pressroom/states/maryland/maryland.htm',
  },
  {
    YEAR: 2017,
    STATE: 'MA',
    RATE: 31.8,
    DEATHS: 2168,
    URL: '/nchs/pressroom/states/massachusetts/massachusetts.htm',
  },
  {
    YEAR: 2017,
    STATE: 'MI',
    RATE: 27.8,
    DEATHS: 2694,
    URL: '/nchs/pressroom/states/michigan/michigan.htm',
  },
  {
    YEAR: 2017,
    STATE: 'MN',
    RATE: 13.3,
    DEATHS: 733,
    URL: '/nchs/pressroom/states/minnesota/minnesota.htm',
  },
  {
    YEAR: 2017,
    STATE: 'MS',
    RATE: 12.2,
    DEATHS: 354,
    URL: '/nchs/pressroom/states/mississippi/mississippi.htm',
  },
  {
    YEAR: 2017,
    STATE: 'MO',
    RATE: 23.4,
    DEATHS: 1367,
    URL: '/nchs/pressroom/states/missouri/missouri.htm',
  },
  {
    YEAR: 2017,
    STATE: 'MT',
    RATE: 11.7,
    DEATHS: 119,
    URL: '/nchs/pressroom/states/montana/montana.htm',
  },
  {
    YEAR: 2017,
    STATE: 'NE',
    RATE: 8.1,
    DEATHS: 152,
    URL: '/nchs/pressroom/states/nebraska/nebraska.htm',
  },
  {
    YEAR: 2017,
    STATE: 'NV',
    RATE: 21.6,
    DEATHS: 676,
    URL: '/nchs/pressroom/states/nevada/nevada.htm',
  },
  {
    YEAR: 2017,
    STATE: 'NH',
    RATE: 37.0,
    DEATHS: 467,
    URL: '/nchs/pressroom/states/newhampshire/newhampshire.htm',
  },
  {
    YEAR: 2017,
    STATE: 'NJ',
    RATE: 30.0,
    DEATHS: 2685,
    URL: '/nchs/pressroom/states/newjersey/newjersey.htm',
  },
  {
    YEAR: 2017,
    STATE: 'NM',
    RATE: 24.8,
    DEATHS: 493,
    URL: '/nchs/pressroom/states/newmexico/newmexico.htm',
  },
  {
    YEAR: 2017,
    STATE: 'NY',
    RATE: 19.4,
    DEATHS: 3921,
    URL: '/nchs/pressroom/states/newyork/newyork.htm',
  },
  {
    YEAR: 2017,
    STATE: 'NC',
    RATE: 24.1,
    DEATHS: 2414,
    URL: '/nchs/pressroom/states/northcarolina/northcarolina.htm',
  },
  {
    YEAR: 2017,
    STATE: 'ND',
    RATE: 9.2,
    DEATHS: 68,
    URL: '/nchs/pressroom/states/northdakota/northdakota.htm',
  },
  {
    YEAR: 2017,
    STATE: 'OH',
    RATE: 46.3,
    DEATHS: 5111,
    URL: '/nchs/pressroom/states/ohio/ohio.htm',
  },
  {
    YEAR: 2017,
    STATE: 'OK',
    RATE: 20.1,
    DEATHS: 775,
    URL: '/nchs/pressroom/states/oklahoma/oklahoma.htm',
  },
  {
    YEAR: 2017,
    STATE: 'OR',
    RATE: 12.4,
    DEATHS: 530,
    URL: '/nchs/pressroom/states/oregon/oregon.htm',
  },
  {
    YEAR: 2017,
    STATE: 'PA',
    RATE: 44.3,
    DEATHS: 5388,
    URL: '/nchs/pressroom/states/pennsylvania/pennsylvania.htm',
  },
  {
    YEAR: 2017,
    STATE: 'RI',
    RATE: 31.0,
    DEATHS: 320,
    URL: '/nchs/pressroom/states/rhodeisland/rhodeisland.htm',
  },
  {
    YEAR: 2017,
    STATE: 'SC',
    RATE: 20.5,
    DEATHS: 1008,
    URL: '/nchs/pressroom/states/southcarolina/southcarolina.htm',
  },
  {
    YEAR: 2017,
    STATE: 'SD',
    RATE: 8.5,
    DEATHS: 73,
    URL: '/nchs/pressroom/states/southdakota/southdakota.htm',
  },
  {
    YEAR: 2017,
    STATE: 'TN',
    RATE: 26.6,
    DEATHS: 1776,
    URL: '/nchs/pressroom/states/tenessee/tennessee.htm',
  },
  {
    YEAR: 2017,
    STATE: 'TX',
    RATE: 10.5,
    DEATHS: 2989,
    URL: '/nchs/pressroom/states/texas/texas.htm',
  },
  {
    YEAR: 2017,
    STATE: 'UT',
    RATE: 22.3,
    DEATHS: 650,
    URL: '/nchs/pressroom/states/utah/utah.htm',
  },
  {
    YEAR: 2017,
    STATE: 'VT',
    RATE: 23.2,
    DEATHS: 134,
    URL: '/nchs/pressroom/states/vermont/vermont.htm',
  },
  {
    YEAR: 2017,
    STATE: 'VA',
    RATE: 17.9,
    DEATHS: 1507,
    URL: '/nchs/pressroom/states/virginia/virginia.htm',
  },
  {
    YEAR: 2017,
    STATE: 'WA',
    RATE: 15.2,
    DEATHS: 1169,
    URL: '/nchs/pressroom/states/washington/washington.htm',
  },
  {
    YEAR: 2017,
    STATE: 'WV',
    RATE: 57.8,
    DEATHS: 974,
    URL: '/nchs/pressroom/states/westvirginia/westvirginia.htm',
  },
  {
    YEAR: 2017,
    STATE: 'WI',
    RATE: 21.2,
    DEATHS: 1177,
    URL: '/nchs/pressroom/states/wisconsin/wisconsin.htm',
  },
  {
    YEAR: 2017,
    STATE: 'WY',
    RATE: 12.2,
    DEATHS: 69,
    URL: '/nchs/pressroom/states/wyoming/wyoming.htm',
  },
  {
    YEAR: 2016,
    STATE: 'AL',
    RATE: 16.2,
    DEATHS: 756,
    URL: '/nchs/pressroom/states/alabama/alabama.htm',
  },
  {
    YEAR: 2016,
    STATE: 'AK',
    RATE: 16.8,
    DEATHS: 128,
    URL: '/nchs/pressroom/states/alaska/alaska.htm',
  },
  {
    YEAR: 2016,
    STATE: 'AZ',
    RATE: 20.3,
    DEATHS: 1382,
    URL: '/nchs/pressroom/states/arizona/arizona.htm',
  },
  {
    YEAR: 2016,
    STATE: 'AR',
    RATE: 14.0,
    DEATHS: 401,
    URL: '/nchs/pressroom/states/arkansas/arkansas.htm',
  },
  {
    YEAR: 2016,
    STATE: 'CA',
    RATE: 11.2,
    DEATHS: 4654,
    URL: '/nchs/pressroom/states/california/california.htm',
  },
  {
    YEAR: 2016,
    STATE: 'CO',
    RATE: 16.6,
    DEATHS: 942,
    URL: '/nchs/pressroom/states/colorado/colorado.htm',
  },
  {
    YEAR: 2016,
    STATE: 'CT',
    RATE: 27.4,
    DEATHS: 971,
    URL: '/nchs/pressroom/states/connecticut/connecticut.htm',
  },
  {
    YEAR: 2016,
    STATE: 'DE',
    RATE: 30.8,
    DEATHS: 282,
    URL: '/nchs/pressroom/states/delaware/delaware.htm',
  },
  {
    YEAR: 2016,
    STATE: 'FL',
    RATE: 23.7,
    DEATHS: 4728,
    URL: '/nchs/pressroom/states/florida/florida.htm',
  },
  {
    YEAR: 2016,
    STATE: 'GA',
    RATE: 13.3,
    DEATHS: 1394,
    URL: '/nchs/pressroom/states/georgia/georgia.htm',
  },
  {
    YEAR: 2016,
    STATE: 'HI',
    RATE: 12.8,
    DEATHS: 191,
    URL: '/nchs/pressroom/states/hawaii/hawaii.htm',
  },
  {
    YEAR: 2016,
    STATE: 'ID',
    RATE: 15.2,
    DEATHS: 243,
    URL: '/nchs/pressroom/states/idaho/idaho.htm',
  },
  {
    YEAR: 2016,
    STATE: 'IL',
    RATE: 18.9,
    DEATHS: 2411,
    URL: '/nchs/pressroom/states/illinois/illinois.htm',
  },
  {
    YEAR: 2016,
    STATE: 'IN',
    RATE: 24.0,
    DEATHS: 1526,
    URL: '/nchs/pressroom/states/indiana/indiana.htm',
  },
  {
    YEAR: 2016,
    STATE: 'IA',
    RATE: 10.6,
    DEATHS: 314,
    URL: '/nchs/pressroom/states/iowa/iowa.htm',
  },
  {
    YEAR: 2016,
    STATE: 'KS',
    RATE: 11.1,
    DEATHS: 313,
    URL: '/nchs/pressroom/states/kansas/kansas.htm',
  },
  {
    YEAR: 2016,
    STATE: 'KY',
    RATE: 33.5,
    DEATHS: 1419,
    URL: '/nchs/pressroom/states/kentucky/kentucky.htm',
  },
  {
    YEAR: 2016,
    STATE: 'LA',
    RATE: 21.8,
    DEATHS: 996,
    URL: '/nchs/pressroom/states/louisiana/louisiana.htm',
  },
  {
    YEAR: 2016,
    STATE: 'ME',
    RATE: 28.7,
    DEATHS: 353,
    URL: '/nchs/pressroom/states/maine/maine.htm',
  },
  {
    YEAR: 2016,
    STATE: 'MD',
    RATE: 33.2,
    DEATHS: 2044,
    URL: '/nchs/pressroom/states/maryland/maryland.htm',
  },
  {
    YEAR: 2016,
    STATE: 'MA',
    RATE: 33.0,
    DEATHS: 2227,
    URL: '/nchs/pressroom/states/massachusetts/massachusetts.htm',
  },
  {
    YEAR: 2016,
    STATE: 'MI',
    RATE: 24.4,
    DEATHS: 2347,
    URL: '/nchs/pressroom/states/michigan/michigan.htm',
  },
  {
    YEAR: 2016,
    STATE: 'MN',
    RATE: 12.5,
    DEATHS: 672,
    URL: '/nchs/pressroom/states/minnesota/minnesota.htm',
  },
  {
    YEAR: 2016,
    STATE: 'MS',
    RATE: 12.1,
    DEATHS: 352,
    URL: '/nchs/pressroom/states/mississippi/mississippi.htm',
  },
  {
    YEAR: 2016,
    STATE: 'MO',
    RATE: 23.6,
    DEATHS: 1371,
    URL: '/nchs/pressroom/states/missouri/missouri.htm',
  },
  {
    YEAR: 2016,
    STATE: 'MT',
    RATE: 11.7,
    DEATHS: 119,
    URL: '/nchs/pressroom/states/montana/montana.htm',
  },
  {
    YEAR: 2016,
    STATE: 'NE',
    RATE: 6.4,
    DEATHS: 120,
    URL: '/nchs/pressroom/states/nebraska/nebraska.htm',
  },
  {
    YEAR: 2016,
    STATE: 'NV',
    RATE: 21.7,
    DEATHS: 665,
    URL: '/nchs/pressroom/states/nevada/nevada.htm',
  },
  {
    YEAR: 2016,
    STATE: 'NH',
    RATE: 39.0,
    DEATHS: 481,
    URL: '/nchs/pressroom/states/newhampshire/newhampshire.htm',
  },
  {
    YEAR: 2016,
    STATE: 'NJ',
    RATE: 23.2,
    DEATHS: 2056,
    URL: '/nchs/pressroom/states/newjersey/newjersey.htm',
  },
  {
    YEAR: 2016,
    STATE: 'NM',
    RATE: 25.2,
    DEATHS: 500,
    URL: '/nchs/pressroom/states/newmexico/newmexico.htm',
  },
  {
    YEAR: 2016,
    STATE: 'NY',
    RATE: 18.0,
    DEATHS: 3638,
    URL: '/nchs/pressroom/states/newyork/newyork.htm',
  },
  {
    YEAR: 2016,
    STATE: 'NC',
    RATE: 19.7,
    DEATHS: 1956,
    URL: '/nchs/pressroom/states/northcarolina/northcarolina.htm',
  },
  {
    YEAR: 2016,
    STATE: 'ND',
    RATE: 10.6,
    DEATHS: 77,
    URL: '/nchs/pressroom/states/northdakota/northdakota.htm',
  },
  {
    YEAR: 2016,
    STATE: 'OH',
    RATE: 39.1,
    DEATHS: 4329,
    URL: '/nchs/pressroom/states/ohio/ohio.htm',
  },
  {
    YEAR: 2016,
    STATE: 'OK',
    RATE: 21.5,
    DEATHS: 813,
    URL: '/nchs/pressroom/states/oklahoma/oklahoma.htm',
  },
  {
    YEAR: 2016,
    STATE: 'OR',
    RATE: 11.9,
    DEATHS: 506,
    URL: '/nchs/pressroom/states/oregon/oregon.htm',
  },
  {
    YEAR: 2016,
    STATE: 'PA',
    RATE: 37.9,
    DEATHS: 4627,
    URL: '/nchs/pressroom/states/pennsylvania/pennsylvania.htm',
  },
  {
    YEAR: 2016,
    STATE: 'RI',
    RATE: 30.8,
    DEATHS: 326,
    URL: '/nchs/pressroom/states/rhodeisland/rhodeisland.htm',
  },
  {
    YEAR: 2016,
    STATE: 'SC',
    RATE: 18.1,
    DEATHS: 879,
    URL: '/nchs/pressroom/states/southcarolina/southcarolina.htm',
  },
  {
    YEAR: 2016,
    STATE: 'SD',
    RATE: 8.4,
    DEATHS: 69,
    URL: '/nchs/pressroom/states/southdakota/southdakota.htm',
  },
  {
    YEAR: 2016,
    STATE: 'TN',
    RATE: 24.5,
    DEATHS: 1630,
    URL: '/nchs/pressroom/states/tenessee/tennessee.htm',
  },
  {
    YEAR: 2016,
    STATE: 'TX',
    RATE: 10.1,
    DEATHS: 2831,
    URL: '/nchs/pressroom/states/texas/texas.htm',
  },
  {
    YEAR: 2016,
    STATE: 'UT',
    RATE: 22.4,
    DEATHS: 635,
    URL: '/nchs/pressroom/states/utah/utah.htm',
  },
  {
    YEAR: 2016,
    STATE: 'VT',
    RATE: 22.2,
    DEATHS: 125,
    URL: '/nchs/pressroom/states/vermont/vermont.htm',
  },
  {
    YEAR: 2016,
    STATE: 'VA',
    RATE: 16.7,
    DEATHS: 1405,
    URL: '/nchs/pressroom/states/virginia/virginia.htm',
  },
  {
    YEAR: 2016,
    STATE: 'WA',
    RATE: 14.5,
    DEATHS: 1102,
    URL: '/nchs/pressroom/states/washington/washington.htm',
  },
  {
    YEAR: 2016,
    STATE: 'WV',
    RATE: 52.0,
    DEATHS: 884,
    URL: '/nchs/pressroom/states/westvirginia/westvirginia.htm',
  },
  {
    YEAR: 2016,
    STATE: 'WI',
    RATE: 19.3,
    DEATHS: 1074,
    URL: '/nchs/pressroom/states/wisconsin/wisconsin.htm',
  },
  {
    YEAR: 2016,
    STATE: 'WY',
    RATE: 17.6,
    DEATHS: 99,
    URL: '/nchs/pressroom/states/wyoming/wyoming.htm',
  },
  {
    YEAR: 2015,
    STATE: 'AL',
    RATE: 15.7,
    DEATHS: 736,
    URL: '/nchs/pressroom/states/alabama/alabama.htm',
  },
  {
    YEAR: 2015,
    STATE: 'AK',
    RATE: 16.0,
    DEATHS: 122,
    URL: '/nchs/pressroom/states/alaska/alaska.htm',
  },
  {
    YEAR: 2015,
    STATE: 'AZ',
    RATE: 19.0,
    DEATHS: 1274,
    URL: '/nchs/pressroom/states/arizona/arizona.htm',
  },
  {
    YEAR: 2015,
    STATE: 'AR',
    RATE: 13.8,
    DEATHS: 392,
    URL: '/nchs/pressroom/states/arkansas/arkansas.htm',
  },
  {
    YEAR: 2015,
    STATE: 'CA',
    RATE: 11.3,
    DEATHS: 4659,
    URL: '/nchs/pressroom/states/california/california.htm',
  },
  {
    YEAR: 2015,
    STATE: 'CO',
    RATE: 15.4,
    DEATHS: 869,
    URL: '/nchs/pressroom/states/colorado/colorado.htm',
  },
  {
    YEAR: 2015,
    STATE: 'CT',
    RATE: 22.1,
    DEATHS: 800,
    URL: '/nchs/pressroom/states/connecticut/connecticut.htm',
  },
  {
    YEAR: 2015,
    STATE: 'DE',
    RATE: 22.0,
    DEATHS: 198,
    URL: '/nchs/pressroom/states/delaware/delaware.htm',
  },
  {
    YEAR: 2015,
    STATE: 'FL',
    RATE: 16.2,
    DEATHS: 3228,
    URL: '/nchs/pressroom/states/florida/florida.htm',
  },
  {
    YEAR: 2015,
    STATE: 'GA',
    RATE: 12.7,
    DEATHS: 1302,
    URL: '/nchs/pressroom/states/georgia/georgia.htm',
  },
  {
    YEAR: 2015,
    STATE: 'HI',
    RATE: 11.3,
    DEATHS: 169,
    URL: '/nchs/pressroom/states/hawaii/hawaii.htm',
  },
  {
    YEAR: 2015,
    STATE: 'ID',
    RATE: 14.2,
    DEATHS: 218,
    URL: '/nchs/pressroom/states/idaho/idaho.htm',
  },
  {
    YEAR: 2015,
    STATE: 'IL',
    RATE: 14.1,
    DEATHS: 1835,
    URL: '/nchs/pressroom/states/illinois/illinois.htm',
  },
  {
    YEAR: 2015,
    STATE: 'IN',
    RATE: 19.5,
    DEATHS: 1245,
    URL: '/nchs/pressroom/states/indiana/indiana.htm',
  },
  {
    YEAR: 2015,
    STATE: 'IA',
    RATE: 10.3,
    DEATHS: 309,
    URL: '/nchs/pressroom/states/iowa/iowa.htm',
  },
  {
    YEAR: 2015,
    STATE: 'KS',
    RATE: 11.8,
    DEATHS: 329,
    URL: '/nchs/pressroom/states/kansas/kansas.htm',
  },
  {
    YEAR: 2015,
    STATE: 'KY',
    RATE: 29.9,
    DEATHS: 1273,
    URL: '/nchs/pressroom/states/kentucky/kentucky.htm',
  },
  {
    YEAR: 2015,
    STATE: 'LA',
    RATE: 19.0,
    DEATHS: 861,
    URL: '/nchs/pressroom/states/louisiana/louisiana.htm',
  },
  {
    YEAR: 2015,
    STATE: 'ME',
    RATE: 21.2,
    DEATHS: 269,
    URL: '/nchs/pressroom/states/maine/maine.htm',
  },
  {
    YEAR: 2015,
    STATE: 'MD',
    RATE: 20.9,
    DEATHS: 1285,
    URL: '/nchs/pressroom/states/maryland/maryland.htm',
  },
  {
    YEAR: 2015,
    STATE: 'MA',
    RATE: 25.7,
    DEATHS: 1724,
    URL: '/nchs/pressroom/states/massachusetts/massachusetts.htm',
  },
  {
    YEAR: 2015,
    STATE: 'MI',
    RATE: 20.4,
    DEATHS: 1980,
    URL: '/nchs/pressroom/states/michigan/michigan.htm',
  },
  {
    YEAR: 2015,
    STATE: 'MN',
    RATE: 10.6,
    DEATHS: 581,
    URL: '/nchs/pressroom/states/minnesota/minnesota.htm',
  },
  {
    YEAR: 2015,
    STATE: 'MS',
    RATE: 12.3,
    DEATHS: 351,
    URL: '/nchs/pressroom/states/mississippi/mississippi.htm',
  },
  {
    YEAR: 2015,
    STATE: 'MO',
    RATE: 17.9,
    DEATHS: 1066,
    URL: '/nchs/pressroom/states/missouri/missouri.htm',
  },
  {
    YEAR: 2015,
    STATE: 'MT',
    RATE: 13.8,
    DEATHS: 138,
    URL: '/nchs/pressroom/states/montana/montana.htm',
  },
  {
    YEAR: 2015,
    STATE: 'NE',
    RATE: 6.9,
    DEATHS: 126,
    URL: '/nchs/pressroom/states/nebraska/nebraska.htm',
  },
  {
    YEAR: 2015,
    STATE: 'NV',
    RATE: 20.4,
    DEATHS: 619,
    URL: '/nchs/pressroom/states/nevada/nevada.htm',
  },
  {
    YEAR: 2015,
    STATE: 'NH',
    RATE: 34.3,
    DEATHS: 422,
    URL: '/nchs/pressroom/states/newhampshire/newhampshire.htm',
  },
  {
    YEAR: 2015,
    STATE: 'NJ',
    RATE: 16.3,
    DEATHS: 1454,
    URL: '/nchs/pressroom/states/newjersey/newjersey.htm',
  },
  {
    YEAR: 2015,
    STATE: 'NM',
    RATE: 25.3,
    DEATHS: 501,
    URL: '/nchs/pressroom/states/newmexico/newmexico.htm',
  },
  {
    YEAR: 2015,
    STATE: 'NY',
    RATE: 13.6,
    DEATHS: 2754,
    URL: '/nchs/pressroom/states/newyork/newyork.htm',
  },
  {
    YEAR: 2015,
    STATE: 'NC',
    RATE: 15.8,
    DEATHS: 1567,
    URL: '/nchs/pressroom/states/northcarolina/northcarolina.htm',
  },
  {
    YEAR: 2015,
    STATE: 'ND',
    RATE: 8.6,
    DEATHS: 61,
    URL: '/nchs/pressroom/states/northdakota/northdakota.htm',
  },
  {
    YEAR: 2015,
    STATE: 'OH',
    RATE: 29.9,
    DEATHS: 3310,
    URL: '/nchs/pressroom/states/ohio/ohio.htm',
  },
  {
    YEAR: 2015,
    STATE: 'OK',
    RATE: 19.0,
    DEATHS: 725,
    URL: '/nchs/pressroom/states/oklahoma/oklahoma.htm',
  },
  {
    YEAR: 2015,
    STATE: 'OR',
    RATE: 12.0,
    DEATHS: 505,
    URL: '/nchs/pressroom/states/oregon/oregon.htm',
  },
  {
    YEAR: 2015,
    STATE: 'PA',
    RATE: 26.3,
    DEATHS: 3264,
    URL: '/nchs/pressroom/states/pennsylvania/pennsylvania.htm',
  },
  {
    YEAR: 2015,
    STATE: 'RI',
    RATE: 28.2,
    DEATHS: 310,
    URL: '/nchs/pressroom/states/rhodeisland/rhodeisland.htm',
  },
  {
    YEAR: 2015,
    STATE: 'SC',
    RATE: 15.7,
    DEATHS: 761,
    URL: '/nchs/pressroom/states/southcarolina/southcarolina.htm',
  },
  {
    YEAR: 2015,
    STATE: 'SD',
    RATE: 8.4,
    DEATHS: 65,
    URL: '/nchs/pressroom/states/southdakota/southdakota.htm',
  },
  {
    YEAR: 2015,
    STATE: 'TN',
    RATE: 22.2,
    DEATHS: 1457,
    URL: '/nchs/pressroom/states/tenessee/tennessee.htm',
  },
  {
    YEAR: 2015,
    STATE: 'TX',
    RATE: 9.4,
    DEATHS: 2588,
    URL: '/nchs/pressroom/states/texas/texas.htm',
  },
  {
    YEAR: 2015,
    STATE: 'UT',
    RATE: 23.4,
    DEATHS: 646,
    URL: '/nchs/pressroom/states/utah/utah.htm',
  },
  {
    YEAR: 2015,
    STATE: 'VT',
    RATE: 16.7,
    DEATHS: 99,
    URL: '/nchs/pressroom/states/vermont/vermont.htm',
  },
  {
    YEAR: 2015,
    STATE: 'VA',
    RATE: 12.4,
    DEATHS: 1039,
    URL: '/nchs/pressroom/states/virginia/virginia.htm',
  },
  {
    YEAR: 2015,
    STATE: 'WA',
    RATE: 14.7,
    DEATHS: 1094,
    URL: '/nchs/pressroom/states/washington/washington.htm',
  },
  {
    YEAR: 2015,
    STATE: 'WV',
    RATE: 41.5,
    DEATHS: 725,
    URL: '/nchs/pressroom/states/westvirginia/westvirginia.htm',
  },
  {
    YEAR: 2015,
    STATE: 'WI',
    RATE: 15.5,
    DEATHS: 878,
    URL: '/nchs/pressroom/states/wisconsin/wisconsin.htm',
  },
  {
    YEAR: 2015,
    STATE: 'WY',
    RATE: 16.4,
    DEATHS: 96,
    URL: '/nchs/pressroom/states/wyoming/wyoming.htm',
  },
  {
    YEAR: 2014,
    STATE: 'AL',
    RATE: 15.2,
    DEATHS: 723,
    URL: '/nchs/pressroom/states/alabama/alabama.htm',
  },
  {
    YEAR: 2014,
    STATE: 'AK',
    RATE: 16.8,
    DEATHS: 124,
    URL: '/nchs/pressroom/states/alaska/alaska.htm',
  },
  {
    YEAR: 2014,
    STATE: 'AZ',
    RATE: 12.6,
    DEATHS: 356,
    URL: '/nchs/pressroom/states/arizona/arizona.htm',
  },
  {
    YEAR: 2014,
    STATE: 'AR',
    RATE: 18.2,
    DEATHS: 1211,
    URL: '/nchs/pressroom/states/arkansas/arkansas.htm',
  },
  {
    YEAR: 2014,
    STATE: 'CA',
    RATE: 11.1,
    DEATHS: 4521,
    URL: '/nchs/pressroom/states/california/california.htm',
  },
  {
    YEAR: 2014,
    STATE: 'CO',
    RATE: 16.3,
    DEATHS: 899,
    URL: '/nchs/pressroom/states/colorado/colorado.htm',
  },
  {
    YEAR: 2014,
    STATE: 'CT',
    RATE: 17.6,
    DEATHS: 623,
    URL: '/nchs/pressroom/states/connecticut/connecticut.htm',
  },
  {
    YEAR: 2014,
    STATE: 'DE',
    RATE: 20.9,
    DEATHS: 189,
    URL: '/nchs/pressroom/states/delaware/delaware.htm',
  },
  {
    YEAR: 2014,
    STATE: 'FL',
    RATE: 13.2,
    DEATHS: 2634,
    URL: '/nchs/pressroom/states/florida/florida.htm',
  },
  {
    YEAR: 2014,
    STATE: 'GA',
    RATE: 11.9,
    DEATHS: 1206,
    URL: '/nchs/pressroom/states/georgia/georgia.htm',
  },
  {
    YEAR: 2014,
    STATE: 'HI',
    RATE: 10.9,
    DEATHS: 157,
    URL: '/nchs/pressroom/states/hawaii/hawaii.htm',
  },
  {
    YEAR: 2014,
    STATE: 'ID',
    RATE: 13.7,
    DEATHS: 212,
    URL: '/nchs/pressroom/states/idaho/idaho.htm',
  },
  {
    YEAR: 2014,
    STATE: 'IL',
    RATE: 13.1,
    DEATHS: 1705,
    URL: '/nchs/pressroom/states/illinois/illinois.htm',
  },
  {
    YEAR: 2014,
    STATE: 'IN',
    RATE: 18.2,
    DEATHS: 1172,
    URL: '/nchs/pressroom/states/indiana/indiana.htm',
  },
  {
    YEAR: 2014,
    STATE: 'IA',
    RATE: 8.8,
    DEATHS: 264,
    URL: '/nchs/pressroom/states/iowa/iowa.htm',
  },
  {
    YEAR: 2014,
    STATE: 'KS',
    RATE: 11.7,
    DEATHS: 332,
    URL: '/nchs/pressroom/states/kansas/kansas.htm',
  },
  {
    YEAR: 2014,
    STATE: 'KY',
    RATE: 24.7,
    DEATHS: 1077,
    URL: '/nchs/pressroom/states/kentucky/kentucky.htm',
  },
  {
    YEAR: 2014,
    STATE: 'LA',
    RATE: 16.9,
    DEATHS: 777,
    URL: '/nchs/pressroom/states/louisiana/louisiana.htm',
  },
  {
    YEAR: 2014,
    STATE: 'ME',
    RATE: 16.8,
    DEATHS: 216,
    URL: '/nchs/pressroom/states/maine/maine.htm',
  },
  {
    YEAR: 2014,
    STATE: 'MD',
    RATE: 17.4,
    DEATHS: 1070,
    URL: '/nchs/pressroom/states/maryland/maryland.htm',
  },
  {
    YEAR: 2014,
    STATE: 'MA',
    RATE: 19.0,
    DEATHS: 1289,
    URL: '/nchs/pressroom/states/massachusetts/massachusetts.htm',
  },
  {
    YEAR: 2014,
    STATE: 'MI',
    RATE: 18.0,
    DEATHS: 1762,
    URL: '/nchs/pressroom/states/michigan/michigan.htm',
  },
  {
    YEAR: 2014,
    STATE: 'MN',
    RATE: 9.6,
    DEATHS: 517,
    URL: '/nchs/pressroom/states/minnesota/minnesota.htm',
  },
  {
    YEAR: 2014,
    STATE: 'MS',
    RATE: 11.6,
    DEATHS: 336,
    URL: '/nchs/pressroom/states/mississippi/mississippi.htm',
  },
  {
    YEAR: 2014,
    STATE: 'MO',
    RATE: 18.2,
    DEATHS: 1067,
    URL: '/nchs/pressroom/states/missouri/missouri.htm',
  },
  {
    YEAR: 2014,
    STATE: 'MT',
    RATE: 12.4,
    DEATHS: 125,
    URL: '/nchs/pressroom/states/montana/montana.htm',
  },
  {
    YEAR: 2014,
    STATE: 'NE',
    RATE: 7.2,
    DEATHS: 125,
    URL: '/nchs/pressroom/states/nebraska/nebraska.htm',
  },
  {
    YEAR: 2014,
    STATE: 'NV',
    RATE: 18.4,
    DEATHS: 545,
    URL: '/nchs/pressroom/states/nevada/nevada.htm',
  },
  {
    YEAR: 2014,
    STATE: 'NH',
    RATE: 26.2,
    DEATHS: 334,
    URL: '/nchs/pressroom/states/newhampshire/newhampshire.htm',
  },
  {
    YEAR: 2014,
    STATE: 'NJ',
    RATE: 14.0,
    DEATHS: 1253,
    URL: '/nchs/pressroom/states/newjersey/newjersey.htm',
  },
  {
    YEAR: 2014,
    STATE: 'NM',
    RATE: 27.3,
    DEATHS: 547,
    URL: '/nchs/pressroom/states/newmexico/newmexico.htm',
  },
  {
    YEAR: 2014,
    STATE: 'NY',
    RATE: 11.3,
    DEATHS: 2300,
    URL: '/nchs/pressroom/states/newyork/newyork.htm',
  },
  {
    YEAR: 2014,
    STATE: 'NC',
    RATE: 13.8,
    DEATHS: 1358,
    URL: '/nchs/pressroom/states/northcarolina/northcarolina.htm',
  },
  {
    YEAR: 2014,
    STATE: 'ND',
    RATE: 6.3,
    DEATHS: 43,
    URL: '/nchs/pressroom/states/northdakota/northdakota.htm',
  },
  {
    YEAR: 2014,
    STATE: 'OH',
    RATE: 24.6,
    DEATHS: 2744,
    URL: '/nchs/pressroom/states/ohio/ohio.htm',
  },
  {
    YEAR: 2014,
    STATE: 'OK',
    RATE: 20.3,
    DEATHS: 777,
    URL: '/nchs/pressroom/states/oklahoma/oklahoma.htm',
  },
  {
    YEAR: 2014,
    STATE: 'OR',
    RATE: 12.8,
    DEATHS: 522,
    URL: '/nchs/pressroom/states/oregon/oregon.htm',
  },
  {
    YEAR: 2014,
    STATE: 'PA',
    RATE: 21.9,
    DEATHS: 2732,
    URL: '/nchs/pressroom/states/pennsylvania/pennsylvania.htm',
  },
  {
    YEAR: 2014,
    STATE: 'RI',
    RATE: 23.4,
    DEATHS: 247,
    URL: '/nchs/pressroom/states/rhodeisland/rhodeisland.htm',
  },
  {
    YEAR: 2014,
    STATE: 'SC',
    RATE: 14.4,
    DEATHS: 701,
    URL: '/nchs/pressroom/states/southcarolina/southcarolina.htm',
  },
  {
    YEAR: 2014,
    STATE: 'SD',
    RATE: 7.8,
    DEATHS: 63,
    URL: '/nchs/pressroom/states/southdakota/southdakota.htm',
  },
  {
    YEAR: 2014,
    STATE: 'TN',
    RATE: 19.5,
    DEATHS: 1269,
    URL: '/nchs/pressroom/states/tenessee/tennessee.htm',
  },
  {
    YEAR: 2014,
    STATE: 'TX',
    RATE: 9.7,
    DEATHS: 2601,
    URL: '/nchs/pressroom/states/texas/texas.htm',
  },
  {
    YEAR: 2014,
    STATE: 'UT',
    RATE: 22.4,
    DEATHS: 603,
    URL: '/nchs/pressroom/states/utah/utah.htm',
  },
  {
    YEAR: 2014,
    STATE: 'VT',
    RATE: 13.9,
    DEATHS: 83,
    URL: '/nchs/pressroom/states/vermont/vermont.htm',
  },
  {
    YEAR: 2014,
    STATE: 'VA',
    RATE: 11.7,
    DEATHS: 980,
    URL: '/nchs/pressroom/states/virginia/virginia.htm',
  },
  {
    YEAR: 2014,
    STATE: 'WA',
    RATE: 13.3,
    DEATHS: 979,
    URL: '/nchs/pressroom/states/washington/washington.htm',
  },
  {
    YEAR: 2014,
    STATE: 'WV',
    RATE: 35.5,
    DEATHS: 627,
    URL: '/nchs/pressroom/states/westvirginia/westvirginia.htm',
  },
  {
    YEAR: 2014,
    STATE: 'WI',
    RATE: 15.1,
    DEATHS: 853,
    URL: '/nchs/pressroom/states/wisconsin/wisconsin.htm',
  },
  {
    YEAR: 2014,
    STATE: 'WY',
    RATE: 19.4,
    DEATHS: 109,
    URL: '/nchs/pressroom/states/wyoming/wyoming.htm',
  },
  {
    YEAR: 2005,
    STATE: 'AL',
    RATE: 6.3,
    DEATHS: 283,
    URL: '/nchs/pressroom/states/alabama/alabama.htm',
  },
  {
    YEAR: 2005,
    STATE: 'AK',
    RATE: 11.4,
    DEATHS: 79,
    URL: '/nchs/pressroom/states/alaska/alaska.htm',
  },
  {
    YEAR: 2005,
    STATE: 'AZ',
    RATE: 14.1,
    DEATHS: 794,
    URL: '/nchs/pressroom/states/arizona/arizona.htm',
  },
  {
    YEAR: 2005,
    STATE: 'AR',
    RATE: 10.1,
    DEATHS: 269,
    URL: '/nchs/pressroom/states/arkansas/arkansas.htm',
  },
  {
    YEAR: 2005,
    STATE: 'CA',
    RATE: 9.0,
    DEATHS: 3214,
    URL: '/nchs/pressroom/states/california/california.htm',
  },
  {
    YEAR: 2005,
    STATE: 'CO',
    RATE: 12.7,
    DEATHS: 608,
    URL: '/nchs/pressroom/states/colorado/colorado.htm',
  },
  {
    YEAR: 2005,
    STATE: 'CT',
    RATE: 8.5,
    DEATHS: 295,
    URL: '/nchs/pressroom/states/connecticut/connecticut.htm',
  },
  {
    YEAR: 2005,
    STATE: 'DE',
    RATE: 7.5,
    DEATHS: 62,
    URL: '/nchs/pressroom/states/delaware/delaware.htm',
  },
  {
    YEAR: 2005,
    STATE: 'FL',
    RATE: 13.5,
    DEATHS: 2371,
    URL: '/nchs/pressroom/states/florida/florida.htm',
  },
  {
    YEAR: 2005,
    STATE: 'GA',
    RATE: 8.2,
    DEATHS: 738,
    URL: '/nchs/pressroom/states/georgia/georgia.htm',
  },
  {
    YEAR: 2005,
    STATE: 'HI',
    RATE: 9.4,
    DEATHS: 126,
    URL: '/nchs/pressroom/states/hawaii/hawaii.htm',
  },
  {
    YEAR: 2005,
    STATE: 'ID',
    RATE: 8.1,
    DEATHS: 109,
    URL: '/nchs/pressroom/states/idaho/idaho.htm',
  },
  {
    YEAR: 2005,
    STATE: 'IL',
    RATE: 8.4,
    DEATHS: 1067,
    URL: '/nchs/pressroom/states/illinois/illinois.htm',
  },
  {
    YEAR: 2005,
    STATE: 'IN',
    RATE: 9.8,
    DEATHS: 610,
    URL: '/nchs/pressroom/states/indiana/indiana.htm',
  },
  {
    YEAR: 2005,
    STATE: 'IA',
    RATE: 4.8,
    DEATHS: 141,
    URL: '/nchs/pressroom/states/iowa/iowa.htm',
  },
  {
    YEAR: 2005,
    STATE: 'KS',
    RATE: 9.1,
    DEATHS: 241,
    URL: '/nchs/pressroom/states/kansas/kansas.htm',
  },
  {
    YEAR: 2005,
    STATE: 'KY',
    RATE: 15.3,
    DEATHS: 638,
    URL: '/nchs/pressroom/states/kentucky/kentucky.htm',
  },
  {
    YEAR: 2005,
    STATE: 'LA',
    RATE: 14.7,
    DEATHS: 661,
    URL: '/nchs/pressroom/states/louisiana/louisiana.htm',
  },
  {
    YEAR: 2005,
    STATE: 'ME',
    RATE: 12.4,
    DEATHS: 163,
    URL: '/nchs/pressroom/states/maine/maine.htm',
  },
  {
    YEAR: 2005,
    STATE: 'MD',
    RATE: 11.4,
    DEATHS: 656,
    URL: '/nchs/pressroom/states/maryland/maryland.htm',
  },
  {
    YEAR: 2005,
    STATE: 'MA',
    RATE: 12.0,
    DEATHS: 780,
    URL: '/nchs/pressroom/states/massachusetts/massachusetts.htm',
  },
  {
    YEAR: 2005,
    STATE: 'MI',
    RATE: 9.8,
    DEATHS: 985,
    URL: '/nchs/pressroom/states/michigan/michigan.htm',
  },
  {
    YEAR: 2005,
    STATE: 'MN',
    RATE: 5.4,
    DEATHS: 282,
    URL: '/nchs/pressroom/states/minnesota/minnesota.htm',
  },
  {
    YEAR: 2005,
    STATE: 'MS',
    RATE: 8.8,
    DEATHS: 248,
    URL: '/nchs/pressroom/states/mississippi/mississippi.htm',
  },
  {
    YEAR: 2005,
    STATE: 'MO',
    RATE: 10.7,
    DEATHS: 608,
    URL: '/nchs/pressroom/states/missouri/missouri.htm',
  },
  {
    YEAR: 2005,
    STATE: 'MT',
    RATE: 10.1,
    DEATHS: 96,
    URL: '/nchs/pressroom/states/montana/montana.htm',
  },
  {
    YEAR: 2005,
    STATE: 'NE',
    RATE: 5.0,
    DEATHS: 86,
    URL: '/nchs/pressroom/states/nebraska/nebraska.htm',
  },
  {
    YEAR: 2005,
    STATE: 'NV',
    RATE: 18.7,
    DEATHS: 457,
    URL: '/nchs/pressroom/states/nevada/nevada.htm',
  },
  {
    YEAR: 2005,
    STATE: 'NH',
    RATE: 10.7,
    DEATHS: 142,
    URL: '/nchs/pressroom/states/newhampshire/newhampshire.htm',
  },
  {
    YEAR: 2005,
    STATE: 'NJ',
    RATE: 9.4,
    DEATHS: 823,
    URL: '/nchs/pressroom/states/newjersey/newjersey.htm',
  },
  {
    YEAR: 2005,
    STATE: 'NM',
    RATE: 20.1,
    DEATHS: 373,
    URL: '/nchs/pressroom/states/newmexico/newmexico.htm',
  },
  {
    YEAR: 2005,
    STATE: 'NY',
    RATE: 4.8,
    DEATHS: 944,
    URL: '/nchs/pressroom/states/newyork/newyork.htm',
  },
  {
    YEAR: 2005,
    STATE: 'NC',
    RATE: 11.4,
    DEATHS: 1000,
    URL: '/nchs/pressroom/states/northcarolina/northcarolina.htm',
  },
  {
    YEAR: 2005,
    STATE: 'ND',
    RATE: 0.0,
    DEATHS: 12,
    URL: '/nchs/pressroom/states/northdakota/northdakota.htm',
  },
  {
    YEAR: 2005,
    STATE: 'OH',
    RATE: 10.9,
    DEATHS: 1243,
    URL: '/nchs/pressroom/states/ohio/ohio.htm',
  },
  {
    YEAR: 2005,
    STATE: 'OK',
    RATE: 13.8,
    DEATHS: 478,
    URL: '/nchs/pressroom/states/oklahoma/oklahoma.htm',
  },
  {
    YEAR: 2005,
    STATE: 'OR',
    RATE: 10.4,
    DEATHS: 386,
    URL: '/nchs/pressroom/states/oregon/oregon.htm',
  },
  {
    YEAR: 2005,
    STATE: 'PA',
    RATE: 13.2,
    DEATHS: 1613,
    URL: '/nchs/pressroom/states/pennsylvania/pennsylvania.htm',
  },
  {
    YEAR: 2005,
    STATE: 'RI',
    RATE: 14.3,
    DEATHS: 156,
    URL: '/nchs/pressroom/states/rhodeisland/rhodeisland.htm',
  },
  {
    YEAR: 2005,
    STATE: 'SC',
    RATE: 9.9,
    DEATHS: 427,
    URL: '/nchs/pressroom/states/southcarolina/southcarolina.htm',
  },
  {
    YEAR: 2005,
    STATE: 'SD',
    RATE: 5.5,
    DEATHS: 40,
    URL: '/nchs/pressroom/states/southdakota/southdakota.htm',
  },
  {
    YEAR: 2005,
    STATE: 'TN',
    RATE: 14.5,
    DEATHS: 872,
    URL: '/nchs/pressroom/states/tenessee/tennessee.htm',
  },
  {
    YEAR: 2005,
    STATE: 'TX',
    RATE: 8.5,
    DEATHS: 1910,
    URL: '/nchs/pressroom/states/texas/texas.htm',
  },
  {
    YEAR: 2005,
    STATE: 'UT',
    RATE: 19.3,
    DEATHS: 438,
    URL: '/nchs/pressroom/states/utah/utah.htm',
  },
  {
    YEAR: 2005,
    STATE: 'VT',
    RATE: 8.5,
    DEATHS: 53,
    URL: '/nchs/pressroom/states/vermont/vermont.htm',
  },
  {
    YEAR: 2005,
    STATE: 'VA',
    RATE: 7.5,
    DEATHS: 581,
    URL: '/nchs/pressroom/states/virginia/virginia.htm',
  },
  {
    YEAR: 2005,
    STATE: 'WA',
    RATE: 13.0,
    DEATHS: 850,
    URL: '/nchs/pressroom/states/washington/washington.htm',
  },
  {
    YEAR: 2005,
    STATE: 'WV',
    RATE: 10.5,
    DEATHS: 184,
    URL: '/nchs/pressroom/states/westvirginia/westvirginia.htm',
  },
  {
    YEAR: 2005,
    STATE: 'WI',
    RATE: 9.3,
    DEATHS: 518,
    URL: '/nchs/pressroom/states/wisconsin/wisconsin.htm',
  },
  {
    YEAR: 2005,
    STATE: 'WY',
    RATE: 4.9,
    DEATHS: 26,
    URL: '/nchs/pressroom/states/wyoming/wyoming.htm',
  },
  {
    YEAR: 1999,
    STATE: 'AL',
    RATE: 3.9,
    DEATHS: 169,
    URL: '/nchs/pressroom/states/alabama/alabama.htm',
  },
  {
    YEAR: 1999,
    STATE: 'AK',
    RATE: 7.5,
    DEATHS: 46,
    URL: '/nchs/pressroom/states/alaska/alaska.htm',
  },
  {
    YEAR: 1999,
    STATE: 'AZ',
    RATE: 10.6,
    DEATHS: 511,
    URL: '/nchs/pressroom/states/arizona/arizona.htm',
  },
  {
    YEAR: 1999,
    STATE: 'AR',
    RATE: 4.4,
    DEATHS: 113,
    URL: '/nchs/pressroom/states/arkansas/arkansas.htm',
  },
  {
    YEAR: 1999,
    STATE: 'CA',
    RATE: 8.1,
    DEATHS: 2662,
    URL: '/nchs/pressroom/states/california/california.htm',
  },
  {
    YEAR: 1999,
    STATE: 'CO',
    RATE: 8.0,
    DEATHS: 349,
    URL: '/nchs/pressroom/states/colorado/colorado.htm',
  },
  {
    YEAR: 1999,
    STATE: 'CT',
    RATE: 9.0,
    DEATHS: 310,
    URL: '/nchs/pressroom/states/connecticut/connecticut.htm',
  },
  {
    YEAR: 1999,
    STATE: 'DE',
    RATE: 6.4,
    DEATHS: 50,
    URL: '/nchs/pressroom/states/delaware/delaware.htm',
  },
  {
    YEAR: 1999,
    STATE: 'FL',
    RATE: 6.4,
    DEATHS: 997,
    URL: '/nchs/pressroom/states/florida/florida.htm',
  },
  {
    YEAR: 1999,
    STATE: 'GA',
    RATE: 3.5,
    DEATHS: 283,
    URL: '/nchs/pressroom/states/georgia/georgia.htm',
  },
  {
    YEAR: 1999,
    STATE: 'HI',
    RATE: 6.5,
    DEATHS: 80,
    URL: '/nchs/pressroom/states/hawaii/hawaii.htm',
  },
  {
    YEAR: 1999,
    STATE: 'ID',
    RATE: 5.3,
    DEATHS: 64,
    URL: '/nchs/pressroom/states/idaho/idaho.htm',
  },
  {
    YEAR: 1999,
    STATE: 'IL',
    RATE: 6.7,
    DEATHS: 825,
    URL: '/nchs/pressroom/states/illinois/illinois.htm',
  },
  {
    YEAR: 1999,
    STATE: 'IN',
    RATE: 3.2,
    DEATHS: 191,
    URL: '/nchs/pressroom/states/indiana/indiana.htm',
  },
  {
    YEAR: 1999,
    STATE: 'IA',
    RATE: 1.9,
    DEATHS: 53,
    URL: '/nchs/pressroom/states/iowa/iowa.htm',
  },
  {
    YEAR: 1999,
    STATE: 'KS',
    RATE: 3.4,
    DEATHS: 89,
    URL: '/nchs/pressroom/states/kansas/kansas.htm',
  },
  {
    YEAR: 1999,
    STATE: 'KY',
    RATE: 4.9,
    DEATHS: 197,
    URL: '/nchs/pressroom/states/kentucky/kentucky.htm',
  },
  {
    YEAR: 1999,
    STATE: 'LA',
    RATE: 4.3,
    DEATHS: 188,
    URL: '/nchs/pressroom/states/louisiana/louisiana.htm',
  },
  {
    YEAR: 1999,
    STATE: 'ME',
    RATE: 5.3,
    DEATHS: 67,
    URL: '/nchs/pressroom/states/maine/maine.htm',
  },
  {
    YEAR: 1999,
    STATE: 'MD',
    RATE: 11.4,
    DEATHS: 629,
    URL: '/nchs/pressroom/states/maryland/maryland.htm',
  },
  {
    YEAR: 1999,
    STATE: 'MA',
    RATE: 7.5,
    DEATHS: 488,
    URL: '/nchs/pressroom/states/massachusetts/massachusetts.htm',
  },
  {
    YEAR: 1999,
    STATE: 'MI',
    RATE: 4.6,
    DEATHS: 460,
    URL: '/nchs/pressroom/states/michigan/michigan.htm',
  },
  {
    YEAR: 1999,
    STATE: 'MN',
    RATE: 2.8,
    DEATHS: 136,
    URL: '/nchs/pressroom/states/minnesota/minnesota.htm',
  },
  {
    YEAR: 1999,
    STATE: 'MS',
    RATE: 3.2,
    DEATHS: 87,
    URL: '/nchs/pressroom/states/mississippi/mississippi.htm',
  },
  {
    YEAR: 1999,
    STATE: 'MO',
    RATE: 5.0,
    DEATHS: 276,
    URL: '/nchs/pressroom/states/missouri/missouri.htm',
  },
  {
    YEAR: 1999,
    STATE: 'MT',
    RATE: 4.6,
    DEATHS: 41,
    URL: '/nchs/pressroom/states/montana/montana.htm',
  },
  {
    YEAR: 1999,
    STATE: 'NE',
    RATE: 2.3,
    DEATHS: 39,
    URL: '/nchs/pressroom/states/nebraska/nebraska.htm',
  },
  {
    YEAR: 1999,
    STATE: 'NV',
    RATE: 11.5,
    DEATHS: 227,
    URL: '/nchs/pressroom/states/nevada/nevada.htm',
  },
  {
    YEAR: 1999,
    STATE: 'NH',
    RATE: 4.3,
    DEATHS: 54,
    URL: '/nchs/pressroom/states/newhampshire/newhampshire.htm',
  },
  {
    YEAR: 1999,
    STATE: 'NJ',
    RATE: 6.5,
    DEATHS: 557,
    URL: '/nchs/pressroom/states/newjersey/newjersey.htm',
  },
  {
    YEAR: 1999,
    STATE: 'NM',
    RATE: 15.0,
    DEATHS: 266,
    URL: '/nchs/pressroom/states/newmexico/newmexico.htm',
  },
  {
    YEAR: 1999,
    STATE: 'NY',
    RATE: 5.0,
    DEATHS: 959,
    URL: '/nchs/pressroom/states/newyork/newyork.htm',
  },
  {
    YEAR: 1999,
    STATE: 'NC',
    RATE: 4.6,
    DEATHS: 366,
    URL: '/nchs/pressroom/states/northcarolina/northcarolina.htm',
  },
  {
    YEAR: 1999,
    STATE: 'ND',
    RATE: 0.0,
    DEATHS: 12,
    URL: '/nchs/pressroom/states/northdakota/northdakota.htm',
  },
  {
    YEAR: 1999,
    STATE: 'OH',
    RATE: 4.2,
    DEATHS: 467,
    URL: '/nchs/pressroom/states/ohio/ohio.htm',
  },
  {
    YEAR: 1999,
    STATE: 'OK',
    RATE: 5.4,
    DEATHS: 178,
    URL: '/nchs/pressroom/states/oklahoma/oklahoma.htm',
  },
  {
    YEAR: 1999,
    STATE: 'OR',
    RATE: 6.1,
    DEATHS: 210,
    URL: '/nchs/pressroom/states/oregon/oregon.htm',
  },
  {
    YEAR: 1999,
    STATE: 'PA',
    RATE: 8.1,
    DEATHS: 990,
    URL: '/nchs/pressroom/states/pennsylvania/pennsylvania.htm',
  },
  {
    YEAR: 1999,
    STATE: 'RI',
    RATE: 5.5,
    DEATHS: 58,
    URL: '/nchs/pressroom/states/rhodeisland/rhodeisland.htm',
  },
  {
    YEAR: 1999,
    STATE: 'SC',
    RATE: 3.7,
    DEATHS: 147,
    URL: '/nchs/pressroom/states/southcarolina/southcarolina.htm',
  },
  {
    YEAR: 1999,
    STATE: 'SD',
    RATE: 0.0,
    DEATHS: 17,
    URL: '/nchs/pressroom/states/southdakota/southdakota.htm',
  },
  {
    YEAR: 1999,
    STATE: 'TN',
    RATE: 6.1,
    DEATHS: 344,
    URL: '/nchs/pressroom/states/tenessee/tennessee.htm',
  },
  {
    YEAR: 1999,
    STATE: 'TX',
    RATE: 5.4,
    DEATHS: 1087,
    URL: '/nchs/pressroom/states/texas/texas.htm',
  },
  {
    YEAR: 1999,
    STATE: 'UT',
    RATE: 10.6,
    DEATHS: 205,
    URL: '/nchs/pressroom/states/utah/utah.htm',
  },
  {
    YEAR: 1999,
    STATE: 'VT',
    RATE: 4.7,
    DEATHS: 29,
    URL: '/nchs/pressroom/states/vermont/vermont.htm',
  },
  {
    YEAR: 1999,
    STATE: 'VA',
    RATE: 5.0,
    DEATHS: 366,
    URL: '/nchs/pressroom/states/virginia/virginia.htm',
  },
  {
    YEAR: 1999,
    STATE: 'WA',
    RATE: 9.3,
    DEATHS: 555,
    URL: '/nchs/pressroom/states/washington/washington.htm',
  },
  {
    YEAR: 1999,
    STATE: 'WV',
    RATE: 4.1,
    DEATHS: 75,
    URL: '/nchs/pressroom/states/westvirginia/westvirginia.htm',
  },
  {
    YEAR: 1999,
    STATE: 'WI',
    RATE: 4.0,
    DEATHS: 212,
    URL: '/nchs/pressroom/states/wisconsin/wisconsin.htm',
  },
  {
    YEAR: 1999,
    STATE: 'WY',
    RATE: 4.1,
    DEATHS: 20,
    URL: '/nchs/pressroom/states/wyoming/wyoming.htm',
  },
];
window.overdoseData = overdoseData;
